# -*- coding: utf-8 -*-
"""
翻译模板和术语表模块
"""

class TranslationTemplates:
    """Dota2专用翻译模板管理器"""
    
    # 英雄简称映射
    HERO_ABBREVIATIONS = {
        "qop": "Queen of Pain",
        "pa": "Phantom Assassin",
        "am": "Anti-Mage",
        "sf": "Shadow Fiend",
        "tb": "Terrorblade",
        "wk": "Wraith King",
        "dk": "Dragon Knight",
        "snk": "Sand King",
        "tiny": "Tiny",
        "tinker": "Tinker",
        "storm": "Storm Spirit",
        "invoker": "Invoker",
        "puck": "Puck",
        "zeus": "Zeus",
        "lina": "Lina",
        "cm": "Crystal Maiden",
        "wd": "Warlock",
        "wd": "Witch Doctor",
        "np": "Nature's Prophet",
        "furion": "Nature's Prophet",
        "bh": "Bounty Hunter",
        "riki": "Riki",
        "sa": "Sand Arrow",
        "pl": "Phantom Lancer",
        "naga": "Naga Siren",
        "spectre": "Spectre",
        "void": "Faceless Void",
        "fv": "Faceless Void",
        "sven": "Sven",
        "kunkka": "Kunkka",
        "clock": "Clockwerk",
        "bb": "Batrider",
        "br": "Bloodseeker",
        "bs": "Bloodseeker",
        "weaver": "Weaver",
        "cs": "Centaur Warrunner",
        "lc": "Legion Commander",
        "axe": "Axe",
        "bm": "Beastmaster",
        "ds": "Dark Seer",
        "doom": "Doom",
        "huskar": "Huskarr",
        "lycan": "Lycan",
        "na": "Nyx Assasin",
        "nyx": "Nyx Assasin",
        "slardar": "Slardar",
        "sl": "Slardar",
        "tide": "Tidehunter",
        "th": "Tidehunter",
        "timbersaw": "Timbersaw",
        "ts": "Timbersaw",
        "treant": "Treant Protector",
        "tp": "Treant Protector",
        "tusk": "Tusk",
        "underlord": "Underlord",
        "ul": "Underlord",
        "abaddon": "Abaddon",
        "aba": "Abaddon",
        "alchemist": "Alchemist",
        "alc": "Alchemist",
        "ancient": "Ancient Apparition",
        "aa": "Ancient Apparition",
        "bane": "Bane",
        "bat": "Batrider",
        "chen": "Chen",
        "clinkz": "Clinkz",
        "ck": "Clinkz",
        "dazzle": "Dazzle",
        "dz": "Dazzle",
        "dp": "Death Prophet",
        "earthshaker": "Earthshaker",
        "es": "Earthshaker",
        "enchantress": "Enchantress",
        "ench": "Enchantress",
        "ench": "Enigma",
        "gg": "Grimstroke",
        "io": "Io",
        "jakiro": "Jakiro",
        "jk": "Jakiro",
        "leshrac": "Leshrac",
        "ls": "Leshrac",
        "lich": "Lich",
        "lion": "Lion",
        "lone": "Lone Druid",
        "ld": "Lone Druid",
        "ogre": "Ogre Magi",
        "om": "Ogre Magi",
        "oracle": "Oracle",
        "od": "Outworld Devourer",
        "od": "Outworld Devourer",
        "pugna": "Pugna",
        "razor": "Razor",
        "rz": "Razor",
        "rubick": "Rubick",
        "rb": "Rubick",
        "sky": "Skywrath Mage",
        "sm": "Skywrath Mage",
        "shadow_shaman": "Shadow Shaman",
        "ss": "Shadow Shaman",
        "silencer": "Silencer",
        "sili": "Silencer",
        "spirit_breaker": "Spirit Breaker",
        "sb": "Spirit Breaker",
        "techies": "Techies",
        "tt": "Techies",
        "visage": "Visage",
        "vg": "Visage",
        "vs": "Vengeful Spirit",
        "viper": "Viper",
        "vp": "Viper",
        "warlock": "Warlock",
        "wl": "Warlock",
        "windrunner": "Windrunner",
        "wr": "Windrunner",
        "winter_wyvern": "Winter Wyvern",
        "ww": "Winter Wyvern",
        "witch_doctor": "Witch Doctor",
        "wd": "Witch Doctor",
        "zo": "Zo",
    }
    
    # 物品名称映射
    ITEM_NAMES = {
        "bkb": "Black King Bar",
        "mkb": "Monkey King Bar",
        "bkb": "Black King Bar",
        "dd": "Diffusal Blade",
        "db": "Diffusal Blade",
        "roshan": "Roshan",
        "aegis": "Aegis of Immortal",
        "cheese": "Cheese",
        "bottle": "Bottle",
        "tp": "Town Portal Scroll",
        "tps": "Town Portal Scroll",
        "dust": "Dust of Appearance",
        "smoke": "Smoke of Deceit",
        "ward": "Observer Ward",
        "sentry": "Sentry Ward",
        "gem": "Gem of True Sight",
        "rapier": "Divine Rapier",
        "blink": "Blink Dagger",
        "force": "Force Staff",
        "eul": "Eul's Scepter of Divinity",
        "euls": "Eul's Scepter of Divinity",
        "veil": "Veil of Discord",
        "nullifier": "Nullifier",
        "orchid": "Orchid Malevolence",
        "bloodthorn": "Bloodthorn",
        "scythe": "Scythe of Vyse",
        "hex": "Scythe of Vyse",
        "refresher": "Refresher Orb",
        "ref": "Refresher Orb",
        "mjollnir": "Mjollnir",
        "mj": "Mjollnir",
        "manta": "Manta Style",
        "ms": "Manta Style",
        "butterfly": "Butterfly",
        "bf": "Battle Fury",
        "bfury": "Battle Fury",
        "abyssal": "Abyssal Blade",
        "ac": "Assault Cuirass",
        "heart": "Heart of Tarrasque",
        "hot": "Heart of Tarrasque",
        "satanic": "Satanic",
        "vladimir": "Vladmir's Offering",
        "vlad": "Vladmir's Offering",
        "crimson": "Crimson Guard",
        "cg": "Crimson Guard",
        "pipe": "Pipe of Insight",
        "lotus": "Lotus Orb",
        "guardian": "Guardian Greaves",
        "gg": "Guardian Greaves",
        "shiva": "Shiva's Guard",
        "sg": "Shiva's Guard",
        "necro": "Necronomicon",
        "dagon": "Dagon",
        "ethereal": "Ethereal Blade",
        "eb": "Ethereal Blade",
        "cyclone": "Eul's Scepter of Divinity",
        "hurricane": "Hurricane Pike",
        "hp": "Hurricane Pike",
        "glimmer": "Glimmer Cape",
        "gc": "Glimmer Cape",
        "solar": "Solar Crest",
        "ascetic": "Ascetic's Cape",
        "aether": "Aether Lens",
        "al": "Aether Lens",
        "arcane": "Arcane Boots",
        "ab": "Arcane Boots",
        "power": "Power Treads",
        "pt": "Power Treads",
        "phase": "Phase Boots",
        "pb": "Phase Boots",
        "tranquil": "Tranquil Boots",
        "tb": "Tranquil Boots",
        "thread": "Power Treads",
        "boots": "Boots of Speed",
        "travel": "Travel Boots",
        "midas": "Hand of Midas",
        "hom": "Hand of Midas",
        "mask": "Mask of Madness",
        "mom": "Mask of Madness",
        "dominator": "Dominator",
        "hotd": "Dominator",
        "vladmirs": "Vladmir's Offering",
        "vod": "Vladmir's Offering",
        "sange": "Sange",
        "yasha": "Yasha",
        "kaya": "Kaya",
        "heavens": "Halberd",
        "hh": "Halberd",
        "dragon": "Dragon Lance",
        "dl": "Dragon Lance",
        "s&y": "Sange and Yasha",
        "sy": "Sange and Yasha",
        "m&k": "Manta Style", 
        "mk": "Manta Style",
        "tri": "Triumvirate",
    }
    
    # 游戏术语映射
    GAME_TERMS = {
        "gank": "抓人",
        "push": "推塔",
        "farm": "打钱",
        "jungle": "打野",
        "roam": "游走",
        "support": "辅助",
        "carry": "核心",
        "offlane": "劣势路",
        "mid": "中路",
        "safe": "优势路",
        "top": "上路",
        "bot": "下路",
        "rosh": "肉山",
        "aegis": "不朽盾",
        "cheese": "奶酪",
        "tp": "传送",
        "b": "回退",
        "miss": "消失",
        "mia": "消失",
        "care": "小心",
        "oom": "没蓝",
        "low hp": "残血",
        "ult": "大招",
        "ulti": "大招",
        "cd": "冷却",
        "mana": "魔法值",
        "hp": "生命值",
        "mp": "魔法值",
        "stun": "眩晕",
        "slow": "减速",
        "silence": "沉默",
        "root": "定身",
        "disarm": "缴械",
        "break": "被动失效",
        "purge": "净化",
        "heal": "治疗",
        "nuke": "爆发伤害",
        "burst": "爆发伤害",
        "dps": "每秒伤害",
        "tank": "坦克",
        "initiate": "先手",
        "counter": "反制",
        "peel": "保人",
        "kite": "风筝",
        "split push": "带线牵制",
        "teamfight": "团战",
        "tf": "团战",
        "team fight": "团战",
        "pick off": "抓单",
        "catch": "抓到",
        "bait": "勾引",
        "dive": "越塔强杀",
        "tower dive": "越塔强杀",
        "backdoor": "偷家",
        "bd": "偷家",
        "defend": "防守",
        "hold": "守塔",
        "rotate": "转线",
        "rotation": "支援",
        "smurf": "炸鱼",
        "feed": "送人头",
        "throw": "翻盘",
        "throwing": "翻盘",
        "thrower": "翻盘怪",
        "comeback": "翻盘",
        "gg": "游戏结束",
        "wp": "打得不错",
        "glhf": "祝好运玩得开心",
        "ty": "谢谢",
        "np": "没问题",
        "sry": "抱歉",
        "my bad": "我的错",
        "mb": "我的错",
        "oops": "哎呀",
        "brb": "马上回来",
        "afk": "挂机",
        "dc": "掉线",
        "lag": "卡顿",
        "ping": "延迟",
        "fps": "帧率",
        "bug": "漏洞",
        "glitch": "故障",
        "crash": "崩溃",
        "freeze": "卡死",
        "desync": "不同步",
        "rubber banding": "回弹",
        "input lag": "输入延迟",
    }
    
    @classmethod
    def translate_hero(cls, text):
        """翻译英雄简称"""
        return cls.HERO_ABBREVIATIONS.get(text.lower(), text)
    
    @classmethod
    def translate_item(cls, text):
        """翻译物品名称"""
        return cls.ITEM_NAMES.get(text.lower(), text)
    
    @classmethod
    def translate_term(cls, text):
        """翻译游戏术语"""
        return cls.GAME_TERMS.get(text.lower(), text)
    
    @classmethod
    def is_hero_abbreviation(cls, text):
        """检查是否为英雄简称"""
        return text.lower() in cls.HERO_ABBREVIATIONS
    
    @classmethod
    def is_item_name(cls, text):
        """检查是否为物品名称"""
        return text.lower() in cls.ITEM_NAMES
    
    @classmethod
    def is_game_term(cls, text):
        """检查是否为游戏术语"""
        return text.lower() in cls.GAME_TERMS
