# -*- coding: utf-8 -*-
"""
Dota2 翻译词库 - 完整优化版 v3.0
基于沟通与分析进行优化，解决术语缺失、映射错误、句式不地道问题
"""

# ==================== 词汇表（中文→英文）====================
ZH_TO_EN = {
    # 英雄名称
    '斧王': 'axe',
    '敌法': 'anti-mage',
    '敌法师': 'anti-mage',
    'am': 'anti-mage',
    '赏金': 'bounty hunter',
    '赏金猎人': 'bounty hunter',
    'bh': 'bounty hunter',
    '兽王': 'beastmaster',
    'bm': 'beastmaster',
    '血魔': 'bloodseeker',
    'bs': 'bloodseeker',
    '牛': 'earthshaker',
    '神牛': 'earthshaker',
    '撼地者': 'earthshaker',
    'es': 'earthshaker',
    '白牛': 'spirit breaker',
    'sb': 'spirit breaker',
    '末日': 'doom',
    '末日使者': 'doom',
    '龙骑': 'dragon knight',
    '龙骑士': 'dragon knight',
    'dk': 'dragon knight',
    '全能': 'omniknight',
    '全能骑士': 'omniknight',
    'omni': 'omniknight',
    '宙斯': 'zeus',
    '冰女': 'crystal maiden',
    'cm': 'crystal maiden',
    '光法': 'keeper of the light',
    'kotl': 'keeper of the light',
    '术士': 'warlock',
    'wl': 'warlock',
    'lion': 'lion',
    '恶魔巫师': 'lion',
    'lina': 'lina',
    '火女': 'lina',
    'wd': 'witch doctor',
    '巫医': 'witch doctor',
    'dp': 'death prophet',
    '死亡先知': 'death prophet',
    'lich': 'lich',
    '巫妖': 'lich',
    'nec': 'necrophos',
    '死灵法': 'necrophos',
    'tk': 'tinker',
    '修补匠': 'tinker',
    '先知': 'natures prophet',
    'np': 'natures prophet',
    'puck': 'puck',
    '精灵龙': 'puck',
    'qop': 'queen of pain',
    '女王': 'queen of pain',
    '骨法': 'pugna',
    'sf': 'shadow fiend',
    '影魔': 'shadow fiend',
    '小Y': 'shadow shaman',
    '暗影萨满': 'shadow shaman',
    'bane': 'bane',
    '祸乱': 'bane',
    '潮汐': 'tidehunter',
    'th': 'tidehunter',
    '抄袭': 'tidehunter',
    '大树': 'treant protector',
    '钢背': 'bristleback',
    'bb': 'bristleback',
    '混沌': 'chaos knight',
    'ck': 'chaos knight',
    '蓝胖': 'ogre magi',
    'om': 'ogre magi',
    '冰魂': 'ancient apparition',
    'aa': 'ancient apparition',
    '屠夫': 'pudge',
    '沙王': 'sand king',
    'sk': 'sand king',
    '蝙蝠': 'batrider',
    'bat': 'batrider',
    '魂守': 'terrorblade',
    'tb': 'terrorblade',
    '幻刺': 'phantom assassin',
    'pa': 'phantom assassin',
    '猴子': 'phantom lancer',
    'pl': 'phantom lancer',
    '小黑': 'drow ranger',
    'drow': 'drow ranger',
    '流浪': 'sven',
    '拍拍': 'ursa',
    '虚空': 'faceless void',
    'void': 'faceless void',
    '幽鬼': 'spectre',
    'spec': 'spectre',
    '水人': 'morphling',
    'morph': 'morphling',
    '小娜迦': 'naga siren',
    'naga': 'naga siren',
    '熊德': 'lone druid',
    'ld': 'lone druid',
    '月骑': 'luna',
    '大娜迦': 'medusa',
    'med': 'medusa',
    '火枪': 'sniper',
    '飞机': 'gyrocopter',
    'gyro': 'gyrocopter',
    '小骷髅': 'clinkz',
    '米波': 'meepo',
    '夜魔': 'night stalker',
    'ns': 'night stalker',
    '蜘蛛': 'broodmother',
    'bm': 'broodmother',
    '隐刺': 'riki',
    '蚂蚁': 'weaver',
    '毒龙': 'viper',
    '剧毒': 'venomancer',
    'veno': 'venomancer',
    '电魂': 'razor',
    '小强': 'nyx assassin',
    'nyx': 'nyx assassin',
    '圣堂': 'templar assassin',
    'ta': 'templar assassin',
    '白虎': 'mirana',
    'potm': 'mirana',
    '复仇': 'vengeful spirit',
    'vs': 'vengeful spirit',
    '小小': 'tiny',
    '海民': 'tusk',
    '拉比克': 'rubick',
    '萨尔': 'disruptor',
    '暗牧': 'dazzle',
    '老鹿': 'leshrac',
    '大牛': 'elder titan',
    'et': 'elder titan',
    '卡尔': 'invoker',
    '沉默': 'silencer',
    '双头龙': 'jakiro',
    '陈': 'chen',
    '小鹿': 'enchantress',
    '炸弹人': 'techies',
    '蓝猫': 'storm spirit',
    'storm': 'storm spirit',
    '火猫': 'ember spirit',
    'ember': 'ember spirit',
    '土猫': 'earth spirit',
    'earth': 'earth spirit',
    '神谕': 'oracle',
    '凤凰': 'phoenix',
    '亚巴顿': 'abaddon',
    '炼金': 'alchemist',
    'alch': 'alchemist',
    '酒仙': 'brewmaster',
    'brew': 'brewmaster',
    '骷髅王': 'wraith king',
    'wk': 'wraith king',
    '小狗': 'lifestealer',
    'ls': 'lifestealer',
    '军团': 'legion commander',
    'lc': 'legion commander',
    '玛尔斯': 'mars',
    '大屁股': 'underlord',
    '尸王': 'undying',
    '墨客': 'grimstroke',
    'grim': 'grimstroke',
    '小仙女': 'dark willow',
    'willow': 'dark willow',
    '松鼠': 'hoodwink',
    '老奶奶': 'snapfire',
    'snap': 'snapfire',
    '剑圣': 'juggernaut',
    'jugg': 'juggernaut',
    '黑鸟': 'outworld devourer',
    'od': 'outworld devourer',
    '猛犸': 'magnus',
    '谜团': 'enigma',
    
    # 物品与术语
    '肉山': 'roshan',
    '否决': 'nullifier',
    '黯灭': 'desolator',
    '微光': 'glimmer cape',
    '吹风': 'euls scepter of divinity',
    'eul': 'euls scepter of divinity',
    '推推': 'force staff',
    'force': 'force staff',
    '跳刀': 'blink dagger',
    'blink': 'blink dagger',
    'bkb': 'black king bar',
    '黑黄': 'black king bar',
    '黑皇': 'black king bar',
    '林肯': 'linkens sphere',
    'linken': 'linkens sphere',
    '羊刀': 'scythe of vyse',
    '紫苑': 'orchid malevolence',
    'orchid': 'orchid malevolence',
    '血棘': 'bloodthorn',
    '血精': 'bloodstone',
    '西瓦': 'shivas guard',
    'shiva': 'shivas guard',
    '冰甲': 'shivas guard',
    '龙心': 'heart of tarrasque',
    'heart': 'heart of tarrasque',
    '强袭': 'assault cuirass',
    'ac': 'assault cuirass',
    '撒旦': 'satanic',
    '冰眼': 'eye of skadi',
    'skadi': 'eye of skadi',
    '大根': 'aghanims scepter',
    'aghs': 'aghanims scepter',
    '神杖': 'aghanims scepter',
    'a杖': 'aghanims scepter',
    '魔晶': 'aghanims shard',
    'shard': 'aghanims shard',
    '刷新': 'refresher orb',
    'refresher': 'refresher orb',
    '飞鞋': 'boots of travel',
    'bot': 'boots of travel',
    '分身': 'manta style',
    'manta': 'manta style',
    '散失': 'diffusal blade',
    'diffusal': 'diffusal blade',
    '虚灵': 'ethereal blade',
    'e blade': 'ethereal blade',
    '阿托斯': 'rod of atos',
    'atos': 'rod of atos',
    '雷锤': 'mjollnir',
    'mjol': 'mjollnir',
    '漩涡': 'maelstrom',
    '大炮': 'daedalus',
    'daed': 'daedalus',
    '金箍棒': 'monkey king bar',
    'mkb': 'monkey king bar',
    '蝴蝶': 'butterfly',
    '辉耀': 'radiance',
    '圣剑': 'divine rapier',
    'rapier': 'divine rapier',
    '深渊': 'abyssal blade',
    'abyssal': 'abyssal blade',
    '梅肯': 'mekansm',
    'mek': 'mekansm',
    '笛子': 'pipe of insight',
    'pipe': 'pipe of insight',
    '纷争': 'veil of discord',
    'veil': 'veil of discord',
    '刃甲': 'blade mail',
    '先锋': 'vanguard',
    '挑战': 'hood of defiance',
    '假腿': 'power treads',
    'pt': 'power treads',
    '相位': 'phase boots',
    '秘法': 'arcane boots',
    '假眼': 'observer ward',
    '真眼': 'sentry ward',
    '眼': 'ward',
    '粉': 'dust of appearance',
    'dust': 'dust of appearance',
    '雾': 'smoke of deceit',
    'smoke': 'smoke of deceit',
    'tp': 'town portal scroll',
    '回城': 'town portal scroll',
    '宝石': 'gem of true sight',
    'gem': 'gem of true sight',
    '芒果': 'enchanted mango',
    'mango': 'enchanted mango',
    '吃树': 'tango',
    '树': 'tango',
    '大药': 'healing salve',
    '小蓝': 'clarity',
    '净化': 'clarity',
    '树枝': 'iron branch',
    '魔棒': 'magic stick',
    '魔杖': 'magic wand',
    '点金': 'hand of midas',
    'midas': 'hand of midas',
    '狂战': 'battle fury',
    'bf': 'battle fury',
    '支配': 'helm of the dominator',
    'hotd': 'helm of the dominator',
    '霸者': 'helm of the overlord',
    'overlord': 'helm of the overlord',
    '死灵书': 'necronomicon',
    'necro': 'necronomicon',
    '隐刀': 'shadow blade',
    '银月': 'silver edge',
    '卫士': 'guardian greaves',
    'gg': 'guardian greaves',
    '莲花': 'lotus orb',
    'lotus': 'lotus orb',
    '赤红': 'crimson guard',
    'crimson': 'crimson guard',
    '炎阳': 'solar crest',
    'solar': 'solar crest',
    '祭品': 'vladmirs offering',
    'vlad': 'vladmirs offering',
    '散夜': 'sange and yasha',
    'sny': 'sange and yasha',
    '疯脸': 'mask of madness',
    'mom': 'mask of madness',
    '护腕': 'bracer',
    '系带': 'wraith band',
    '挂件': 'null talisman',
    '骨灰': 'urn of shadows',
    'urn': 'urn of shadows',
    '韧鼓': 'drum of endurance',
    '天堂': 'heavens halberd',
    '玲珑': 'octarine core',
    '绿杖': 'ghost scepter',
    '不朽盾': 'aegis of the immortal',
    'aegis': 'aegis of the immortal',
    '盾': 'aegis of the immortal',
    '奶酪': 'cheese',
    '赏金符': 'bounty rune',
    '双倍符': 'double damage rune',
    '双倍': 'double damage',
    'dd': 'double damage',
    '隐身符': 'invisibility rune',
    '隐身': 'invisibility',
    'invis': 'invisibility',
    '急速符': 'haste rune',
    '急速': 'haste',
    '恢复符': 'regeneration rune',
    '恢复': 'regeneration',
    'regen': 'regeneration',
    '幻象符': 'illusion rune',
    '奥术符': 'arcane rune',
    '信使': 'courier',
    '鸡': 'courier',
    
    # 游戏机制
    'gank': 'gank',
    '抓人': 'gank',
    'farm': 'farm',
    '发育': 'farm',
    '打钱': 'farm',
    '刷钱': 'farm',
    '补刀': 'last hit',
    '正补': 'last hit',
    '反补': 'deny',
    'deny': 'deny',
    '拉野': 'stack',
    '堆野': 'stack',
    'stack': 'stack',
    'pull': 'pull',
    '拉兵': 'pull',
    '控线': 'control lane',
    '野区': 'jungle',
    'jungle': 'jungle',
    '打野': 'jungle',
    '分路': 'lane',
    'lane': 'lane',
    '上路': 'top',
    'top': 'top',
    '上': 'top',
    '中': 'mid',
    '下': 'bot',
    '中路': 'mid',
    'mid': 'mid',
    '下路': 'bot',
    'bot': 'bot',
    '劣势路': 'offlane',
    'offlane': 'offlane',
    '优势路': 'safelane',
    'safelane': 'safelane',
    '核心': 'carry',
    'carry': 'carry',
    '大哥': 'carry',
    '辅助': 'support',
    'support': 'support',
    '中单': 'mid',
    '肉盾': 'tank',
    'tank': 'tank',
    '爆发': 'burst',
    'burst': 'burst',
    '控制': 'crowd control',
    'cc': 'crowd control',
    '先手': 'initiate',
    'initiate': 'initiate',
    '逃生': 'escape',
    'escape': 'escape',
    '推进': 'pusher',
    'pusher': 'pusher',
    '没蓝': 'out of mana',
    'oom': 'out of mana',
    '没血': 'low hp',
    '没大': 'no ult',
    'ult': 'ultimate',
    'ultimate': 'ultimate',
    '大招': 'ultimate',
    '买活': 'buyback',
    'buyback': 'buyback',
    '掉线': 'disconnected',
    'dc': 'disconnected',
    '挂机': 'afk',
    'afk': 'afk',
    '举报': 'report',
    'report': 'report',
    '集火': 'focus fire',
    'focus': 'focus fire',
    '晕': 'stun',
    'stun': 'stun',
    '沉默': 'silence',
    'silence': 'silence',
    '撤退': 'fall back',
    'back': 'fall back',
    '小心': 'careful',
    'care': 'careful',
    '好局': 'gg',
    'gg': 'gg',
    '玩得好': 'well played',
    'wp': 'well played',
    '漂亮': 'nice',
    'nice': 'nice',
    '抱歉': 'sorry',
    'sorry': 'sorry',
    '我的错': 'my bad',
    'my bad': 'my bad',
    '卡': 'lag',
    'lag': 'lag',
    '点赞': 'commend',
    'commend': 'commend',
    '送人头': 'feed',
    'feed': 'feed',
    '别送': 'dont feed',
    '稳住': 'play safe',
    '翻盘': 'comeback',
    'comeback': 'comeback',
    '上头': 'tilt',
    'tilt': 'tilt',
    '送优势': 'throw',
    'throw': 'throw',
    '削弱': 'nerf',
    'nerf': 'nerf',
    '增强': 'buff',
    'buff': 'buff',
    '强势': 'overpowered',
    'op': 'overpowered',
    '弱势': 'weak',
    '天梯': 'ranked',
    'ranked': 'ranked',
    '排位': 'ranked',
    '路人局': 'pub',
    'pub': 'pub',
    '版本': 'patch',
    'patch': 'patch',
    '带线': 'split push',
    '冲塔': 'dive',
    'dive': 'dive',
    '风筝': 'kite',
    'kite': 'kite',
    '保护': 'peel',
    'peel': 'peel',
    '消耗': 'poke',
    'poke': 'poke',
    '续航': 'sustain',
    'sustain': 'sustain',
    '开团': 'engage',
    'engage': 'engage',
    '撤退': 'disengage',
    'disengage': 'disengage',
    '抢人头': 'kill steal',
    'ks': 'kill steal',
    '滚雪球': 'snowball',
    'snowball': 'snowball',
    'miss': 'missing',
    'missing': 'missing',
    '不见了': 'missing',
    '回来了': 'returned',
    '追': 'chase',
    'chase': 'chase',
    '别追': 'dont chase',
    'go': 'go',
    '来': 'come',
    'come': 'come',
    '守': 'defend',
    'defend': 'defend',
    '推': 'push',
    'push': 'push',
    '杀': 'kill',
    'kill': 'kill',
    '打': 'hit',
    'hit': 'hit',
    '清': 'clear',
    'clear': 'clear',
    '收': 'farm',
    '刷': 'farm',
    '钱': 'gold',
    'gold': 'gold',
    '经验': 'experience',
    'exp': 'experience',
    '等级': 'level',
    'level': 'level',
    '装备': 'item',
    'item': 'item',
    '鞋子': 'boots',
    'boots': 'boots',
    '鞋': 'boots',
    '力量': 'strength',
    'str': 'strength',
    '敏捷': 'agility',
    'agi': 'agility',
    '智力': 'intelligence',
    'int': 'intelligence',
    '攻击': 'attack',
    'attack': 'attack',
    '护甲': 'armor',
    'armor': 'armor',
    '生命': 'health',
    'hp': 'health',
    '魔法': 'mana',
    'mana': 'mana',
    '伤害': 'damage',
    'damage': 'damage',
    'dps': 'dps',
    '远程': 'ranged',
    '近战': 'melee',
    '物理': 'physical',
    '魔法': 'magical',
    '真实': 'pure',
    '魔免': 'magic immune',
    '减速': 'slow',
    'slow': 'slow',
    '加速': 'movement speed',
    'speed': 'movement speed',
    '眩晕': 'stun',
    '缴械': 'disarm',
    'disarm': 'disarm',
    '恐惧': 'fear',
    'fear': 'fear',
    '魅惑': 'charm',
    'charm': 'charm',
    '无敌': 'invulnerable',
    '闪避': 'evasion',
    '暴击': 'critical strike',
    'crit': 'critical strike',
    '吸血': 'lifesteal',
    'lifesteal': 'lifesteal',
    '分裂': 'cleave',
    'cleave': 'cleave',
    '格挡': 'block',
    '恢复': 'heal',
    'heal': 'heal',
    '治疗': 'heal',
    '回蓝': 'mana regeneration',
    '回血': 'health regeneration',
    '视野': 'vision',
    'vision': 'vision',
    '高地': 'high ground',
    '河道': 'river',
    '树林': 'trees',
    
    # 新增高频术语
    '偷盾': 'steal aegis',
    '偷塔': 'backdoor',
    '反眼': 'deward',
    '做眼': 'ward',
    '开雾': 'smoke gank',
    '开5': 'smoke gank',
    '宝石丢了': 'gem lost',
    '有宝石': 'have gem',
    '前哨': 'outpost',
    '天赋': 'talent',
    '控符': 'secure rune',
    '符': 'rune',
    '兵线': 'lane creeps',
    '线': 'lane',
    '进野': 'enter jungle',
    '钻野': 'farm jungle',
    '打远古': 'farm ancient',
    '远古野': 'ancient camp',
    '大野点': 'large camp',
    '小野点': 'small camp',
    '屯野': 'stack camp',
    '拉仇恨': 'draw aggro',
    '仇恨': 'aggro',
    '冲泉': 'dive fountain',
    '泉水': 'fountain',
    '家': 'fountain',
    '读秒': 'respawn timer',
    '复活': 'respawn',
    '死了': 'dead',
    '击杀': 'kill',
    '助攻': 'assist',
    '反杀': 'turn around kill',
    '换命': 'trade kill',
    '一换一': 'one for one',
    '白给': 'die for free',
    '空大': 'miss ultimate',
    '空技能': 'miss skill',
    '技能cd': 'skill on cooldown',
    '没技能': 'no skills up',
    '技能好了': 'skill ready',
    '状态好': 'in good condition',
    '状态差': 'in bad condition',
    '没状态': 'no condition',
    '回家': 'go back to base',
    '回补': 'go back to replenish',
    '更新': 'buy items',
    '出装': 'item build',
    '关键装': 'key item',
    '后期': 'late game',
    '中期': 'mid game',
    '前期': 'early game',
    '对线期': 'lanning stage',
    '出门装': 'starting items',
    '一号位': 'position 1',
    '二号位': 'position 2',
    '三号位': 'position 3',
    '四号位': 'position 4',
    '五号位': 'position 5',
    '硬控': 'hard cc',
    '软控': 'soft cc',
    '点控': 'single target cc',
    '团控': 'aoe cc',
    'aoe': 'area of effect',
    '普攻': 'auto attack',
    '平a': 'auto attack',
    '无视技能免疫': 'pierces spell immunity',
    '驱散': 'dispels',
    '不可驱散': 'undispellable',
    '缠绕': 'root',
    '锁闭': 'break',
    '破被动': 'break',
    '致盲': 'blind',
    '缚灵锁': 'gleipnir',
    '缚灵': 'gleipnir',
    '陨星锤': 'meteor hammer',
    '魂泪': 'magic stick',
    '魔瓶': 'bottle',
    '瓶子': 'bottle',
    '魂戒': 'soul ring',
    '战鼓': 'drum of endurance',
    '秘法鞋': 'arcane boots',
    '相位鞋': 'phase boots',
    '飞鞋': 'boots of travel',
    '静谧之鞋': 'tranquil boots',
    '绿鞋': 'tranquil boots',
    '草鞋': 'boots of speed',
    '补刀斧': 'quelling blade',
    '系带': 'wraith band',
    '挂件': 'null talisman',
    '天鹰戒': 'ring of aquila',
    '魔龙枪': 'dragon lance',
    '飓风长戟': 'hurricane pike',
    '飓风': 'hurricane pike',
    '隐刀': 'shadow blade',
    '白银之锋': 'silver edge',
    '漩涡': 'maelstrom',
    '雷神之锤': 'mjollnir',
    '大电锤': 'mjollnir',
    '水晶剑': 'crystalys',
    '代达罗斯之殇': 'daedalus',
    '金箍棒': 'monkey king bar',
    '蝴蝶': 'butterfly',
    '圣剑': 'divine rapier',
    '吸血面具': 'morbid mask',
    '支配头盔': 'helm of the dominator',
    '魔眼': 'helm of the dominator',
    '吸血鬼的祭品': 'vladmirs offering',
    '散华': 'sange',
    '夜叉': 'yasha',
    '散夜对剑': 'sange and yasha',
    '对剑': 'sange and yasha',
    '慧光': 'kaya',
    '魂之灵瓮': 'urn of shadows',
    '洞察烟斗': 'pipe of insight',
    '烟斗': 'pipe of insight',
    '梅肯斯姆': 'mekansm',
    '卫士胫甲': 'guardian greaves',
    '阿哈利姆神杖': 'aghanims scepter',
    '阿哈利姆魔晶': 'aghanims shard',
    '刷新球': 'refresher orb',
    '清莲宝珠': 'lotus orb',
    '黑皇杖': 'black king bar',
    '林肯法球': 'linkens sphere',
    '永恒之盘': 'aeon disk',
    '永恒': 'aeon disk',
    '否决坠饰': 'nullifier',
    '原力法杖': 'force staff',
    '风杖': 'euls scepter of divinity',
    '虚灵之刃': 'ethereal blade',
    '虚灵刀': 'ethereal blade',
    '达贡之神力': 'dagon',
    '红杖': 'dagon',
    '阿托斯之棍': 'rod of atos',
    '紫怨': 'orchid malevolence',
    '西瓦的守护': 'shivas guard',
    '强袭装甲': 'assault cuirass',
    '恐鳌之心': 'heart of tarrasque',
    '撒旦之邪力': 'satanic',
    '斯嘉蒂之眼': 'eye of skadi',
    '辉耀': 'radiance',
    '银月之晶': 'moon shard',
    '神符': 'rune',
    '智慧神符': 'arcane rune',
    '双倍神符': 'double damage rune',
    '极速神符': 'haste rune',
    '幻象神符': 'illusion rune',
    '隐身神符': 'invisibility rune',
    '恢复神符': 'regeneration rune',
    '护盾神符': 'shield rune',
    '肉山盾': 'aegis',
    '刷新球碎片': 'refresher shard',
    '刷新碎片': 'refresher shard',
    '阿哈利姆福佑': 'aghanims blessing',
    '福佑': 'aghanims blessing',
    '魔瓶': 'bottle',
    '治疗药膏': 'healing salve',
    '魔法芒果': 'enchanted mango',
    '仙灵之火': 'faerie fire',
    '仙火': 'faerie fire',
    '诡计之雾': 'smoke of deceit',
    '显影之尘': 'dust of appearance',
    '飞行信使': 'flying courier',
    '鸟': 'courier',
    '小鸡': 'courier',
    '圣坛': 'shrine',
    '锅': 'shrine',
    '血泉': 'fountain',
    '老家': 'fountain',
    '基地': 'ancient',
    '世界之树': 'ancient',
    '冰封王座': 'ancient',
    '近战兵营': 'melee barracks',
    '远程兵营': 'ranged barracks',
    '兵营': 'barracks',
    '门牙塔': 'tier 4 tower',
    '双子塔': 'tier 4 tower',
    '高地塔': 'tier 3 tower',
    '二塔': 'tier 2 tower',
    '一塔': 'tier 1 tower',
    '外塔': 'tier 1 tower',
    '塔': 'tower',
    '防御塔': 'tower',
    '肉山巢穴': 'roshan pit',
}

# ==================== 词汇表（英文→中文）自动生成 + 手动修正 ====================
AUTO_EN_TO_ZH = {v: k for k, v in ZH_TO_EN.items() if isinstance(v, str)}

MANUAL_EN_TO_ZH = {
    'roshan': '肉山',
    'aegis': '不朽盾',
    'cheese': '奶酪',
    'blink dagger': '跳刀',
    'blink': '跳刀',
    'black king bar': 'bkb',
    'bkb': 'bkb',
    'scythe of vyse': '羊刀',
    'sheepstick': '羊刀',
    'ghost scepter': '绿杖',
    'ethereal blade': '虚灵刀',
    'sentry ward': '真眼',
    'observer ward': '假眼',
    'dust of appearance': '粉',
    'dust': '粉',
    'smoke of deceit': '雾',
    'smoke': '雾',
    'gem of true sight': '宝石',
    'gem': '宝石',
    
    'ward': '眼',
    'tp': 'tp',
    'town portal scroll': 'tp',
    'rune': '符',
    'farm': '刷钱',
    'jungle': '打野',
    'gank': '抓人',
    'push': '推',
    'defend': '守',
    'initiate': '先手',
    'stun': '晕',
    'crowd control': '控制',
    'cc': '控制',
    'disable': '控制',
    'ultimate': '大招',
    'ult': '大招',
    'buyback': '买活',
    'stack': '拉野',
    'pull': '拉兵',
    'deward': '反眼',
    'missing': 'miss',
    'mia': 'miss',
    
    'mid': '中',
    'top': '上',
    'bot': '下',
    'mid lane': '中路',
    'top lane': '上路',
    'bot lane': '下路',
    'side lane': '边路',
    'sidelane': '边路',
    'offlane': '劣势路',
    'safelane': '优势路',
    'high ground': '高地',
    'river': '河道',
    'ancient': '远古',
    'fountain': '泉水',
    'base': '泉水',
    
    'first blood': '一血',
    'double kill': '双杀',
    'triple kill': '三杀',
    'team wipe': '团灭',
    'wiped': '团灭',
    'kill': '击杀',
    'died': '死了',
    'dead': '死了',
    'low hp': '没血',
    'out of mana': '没蓝',
    'oom': '没蓝',
    'no ult': '没大',
    'ult ready': '大有好了',
    'respawn': '复活',
    'afk': '挂机',
    'report': '举报',
    'focus fire': '集火',
    'focus': '集火',
    'feed': '送',
    'dont feed': '别送',
    'throw': '浪',
    'dont throw': '别浪',
    'play safe': '稳住',
    'gg': '好局',
    'well played': '打得好',
    'wp': '打得好',
    'nice': '漂亮',
    'commend': '点赞',
    'tilt': '上头',
    'comeback': '翻盘',
    'backdoor': '偷塔',
    'kill steal': '抢人头',
    'ks': '抢人头',
    'dive': '冲塔',
    'kite': '风筝',
    'peel': '保护',
    'poke': '消耗',
    'split push': '带线',
    'smoke gank': '开雾',
    
    'anti-mage': '敌法',
    'tidehunter': '潮汐',
    'magnus': '猛犸',
    'enigma': '谜团',
    'faceless void': '虚空',
    'storm spirit': '蓝猫',
    'outworld devourer': '黑鸟',
    'juggernaut': '剑圣',
    'phantom assassin': '幻刺',
    'shadow fiend': '影魔',
    'terrorblade': '魂守',
    'wraith king': '骷髅王',
    'lifestealer': '小狗',
    'legion commander': '军团',
    'dark willow': '小仙女',
    'snapfire': '老奶奶',
    'hoodwink': '松鼠',
    
    'nullifier': '否决',
    'desolator': '黯灭',
    'glimmer cape': '微光',
    'euls scepter of divinity': '吹风',
    'force staff': '推推',
    'linkens sphere': '林肯',
    'orchid malevolence': '紫苑',
    'bloodthorn': '血棘',
    'bloodstone': '血精',
    'shivas guard': '西瓦',
    'heart of tarrasque': '龙心',
    'assault cuirass': '强袭',
    'satanic': '撒旦',
    'eye of skadi': '冰眼',
    'aghanims scepter': 'a杖',
    'aghanims shard': '魔晶',
    'refresher orb': '刷新',
    'boots of travel': '飞鞋',
    'manta style': '分身',
    'diffusal blade': '散失',
    'rod of atos': '阿托斯',
    'mjollnir': '雷锤',
    'daedalus': '大炮',
    'monkey king bar': '金箍棒',
    'butterfly': '蝴蝶',
    'radiance': '辉耀',
    'divine rapier': '圣剑',
    'abyssal blade': '深渊',
    'mekansm': '梅肯',
    'pipe of insight': '笛子',
    'veil of discord': '纷争',
    'blade mail': '刃甲',
    'vanguard': '先锋',
    'hood of defiance': '挑战',
    'power treads': '假腿',
    'phase boots': '相位',
    'arcane boots': '秘法',
    'observer ward': '假眼',
    'sentry ward': '真眼',
    'dust of appearance': '粉',
    'smoke of deceit': '雾',
    'gem of true sight': '宝石',
    'enchanted mango': '芒果',
    'tango': '吃树',
    'healing salve': '大药',
    'clarity': '小蓝',
    'iron branch': '树枝',
    'magic stick': '魔棒',
    'magic wand': '魔杖',
    'hand of midas': '点金',
    'battle fury': '狂战',
    'helm of the dominator': '支配',
    'helm of the overlord': '霸者',
    'necronomicon': '死灵书',
    'shadow blade': '隐刀',
    'silver edge': '银月',
    'guardian greaves': '卫士',
    'lotus orb': '莲花',
    'crimson guard': '赤红',
    'solar crest': '炎阳',
    'vladmirs offering': '祭品',
    'sange and yasha': '散夜',
    'mask of madness': '疯脸',
    'bracer': '护腕',
    'wraith band': '系带',
    'null talisman': '挂件',
    'urn of shadows': '骨灰',
    'drum of endurance': '韧鼓',
}

EN_TO_ZH = {**AUTO_EN_TO_ZH, **MANUAL_EN_TO_ZH}
EN_TO_ZH = dict(sorted(EN_TO_ZH.items(), key=lambda x: len(x[0]), reverse=True))

# ==================== 短语模板（中文→英文）====================
PHRASE_TEMPLATES_ZH_TO_EN = {
    '肉山在': 'roshan is up',
    '肉山没了': 'roshan is dead',
    '肉山在吗': 'roshan is up',
    '肉山没了吗': 'roshan is dead',
    '肉山快刷了': 'roshan about to spawn',
    '肉山刷新了': 'roshan spawned',
    '肉山处插眼': 'ward roshan',
    '肉山位置插眼': 'ward roshan',
    '打肉山集合': 'do roshan group up',
    '准备打肉山': 'prepare for roshan',
    '去打肉山': 'go do roshan',
    '肉山还活着': 'roshan alive',
    '对面在打盾': 'enemy doing roshan',
    '去抢盾': 'contest roshan',
    '拿到不朽盾': 'got aegis',
    '拿到盾了': 'got aegis',
    '帮我带粉': 'buy dust for me',
    '帮我买': 'buy for me',
    '帮我带个粉过来': 'buy dust for me',
    '帮我买两个眼谢谢': 'help me buy two wards',
    '开否决留人': 'use nullifier to lock them down',
    '开bkb打他快上啊': 'use bkb and fight',
    '有买活可以': 'we have buyback ready',
    '有买活可以打': 'we have buyback ready can fight',
    '守住我们赢': 'defend and we win',
    'tp回防': 'tp back defend',
    'tp过来守塔快': 'tp here defend tower',
    '稳住发育别浪': 'play safe and farm',
    '抄袭开大了快打': 'tidehunter use ravage',
    '白虎去中路了快来': 'mirana goes mid',
    '敌法去下路发育': 'am goes bot farm',
    
    '帮我买一个眼': 'buy a ward for me',
    '帮我买个眼': 'buy a ward for me',
    '帮我买眼': 'buy ward for me',
    '帮我买两个眼': 'buy two wards for me',
    '帮我买真眼': 'buy sentry for me',
    '帮我买假眼': 'buy observer for me',
    '帮我买粉': 'buy dust for me',
    '帮我买雾': 'buy smoke for me',
    '帮我带个粉': 'get dust for me',
    '帮我带个眼': 'get ward for me',
    '帮我带粉': 'get dust for me',
    '帮我带眼': 'get ward for me',
    '买眼': 'buy ward',
    '买真眼': 'buy sentry',
    '买假眼': 'buy observer',
    '买粉': 'buy dust',
    '买雾': 'buy smoke',
    '买个眼': 'buy a ward',
    '买个真眼': 'buy a sentry',
    '整把跳刀': 'get a blink',
    '整把bkb': 'get a bkb',
    '要个笛子': 'need a pipe',
    '出把吹风': 'get an eul',
    '出把否决': 'get a nullifier',
    '出把黯灭': 'get a desolator',
    
    '来中': 'come mid',
    '来上': 'come top',
    '来下': 'come bot',
    '来抓': 'come gank',
    '来抓中': 'come gank mid',
    '来抓上': 'come gank top',
    '来抓下': 'come gank bot',
    '去中': 'go mid',
    '去上': 'go top',
    '去下': 'go bot',
    '去抓': 'go gank',
    '去抓中': 'go gank mid',
    '去抓上': 'go gank top',
    '去抓下': 'go gank bot',
    '下来': 'come bot',
    '下来抓': 'come bot gank',
    '去上抓': 'go top gank',
    
    '白虎去中': 'mirana go mid',
    '敌法去下': 'am go bot',
    '末日去野': 'doom go jungle',
    '蝙蝠去上': 'batrider go top',
    
    '中miss': 'mid missing',
    '中miss了': 'mid missing',
    '上miss': 'top missing',
    '下miss': 'bot missing',
    '中路miss': 'mid missing',
    '上路miss': 'top missing',
    '下路miss': 'bot missing',
    
    '开否决': 'use nullifier',
    '开微光': 'use glimmer',
    '开吹风': 'use eul',
    '开bkb': 'use bkb',
    '开跳刀': 'use blink',
    '开雾': 'use smoke',
    '开虚灵': 'use ethereal blade',
    '开撒旦': 'use satanic',
    '开分身': 'use manta',
    '开羊刀': 'use hex',
    '开紫苑': 'use orchid',
    '开血棘': 'use bloodthorn',
    '开推推': 'use force staff',
    
    '晕他': 'stun him',
    '晕住': 'stun',
    '沉默': 'silence',
    '沉默他': 'silence him',
    '推他': 'force staff him',
    '吹他': 'eul him',
    '羊他': 'hex him',
    
    '抄袭大了': 'ravage',
    '抄袭放大': 'ravage used',
    '猛犸大了': 'echo slam',
    '谜团大了': 'black hole',
    '虚空大了': 'chronosphere',
    '抄袭跳大': 'blink ravage',
    '猛犸跳大': 'blink echo slam',
    '谜团跳大': 'blink black hole',
    '虚空跳大': 'blink chronosphere',
    
    '守塔': 'defend tower',
    '推塔': 'push tower',
    '守高': 'defend high ground',
    '守高地': 'defend high ground',
    '上高': 'push high ground',
    '上高地': 'push high ground',
    '别上高': 'dont push high ground',
    '别上高地': 'dont push high ground',
    
    '有买': 'have buyback',
    '有买活': 'have buyback',
    '没买': 'no buyback',
    '没买活': 'no buyback',
    '无买活': 'no buyback',
    'tp来': 'tp here',
    'tp回': 'tp back',
    'tp守': 'tp defend',
    
    '刷钱': 'farm',
    '发育': 'farm',
    '打钱': 'farm',
    '打野': 'jungle',
    '去野': 'go jungle',
    '去发育': 'go farm',
    '我去打野了': 'going to jungle',
    '去上路发育': 'go top farm',
    '去下路发育': 'go bot farm',
    '去中路发育': 'go mid farm',
    '刷钱别打架': 'farm dont fight',
    '刷完野区回城': 'finish jungle then back',
    '去远古野刷钱': 'farm ancient camps',
    '我去拉野': 'im stacking camps',
    '别抢我野怪': 'dont steal my camps',
    '刷钱更新装备': 'farm for items',
    
    '可以打': 'can fight',
    '能打': 'can fight',
    '打不了': 'cannot fight',
    '不能打': 'cannot fight',
    '可以推': 'can push',
    '能推': 'can push',
    '推不了': 'cannot push',
    
    '别送': 'dont feed',
    '别浪': 'dont throw',
    '稳住': 'play safe',
    '小心': 'be careful',
    '撤退': 'fall back',
    '回来': 'get back',
    '等我': 'wait for me',
    '集合': 'group up',
    '抱团': 'group up',
    '打团': 'teamfight',
    '开团': 'initiate',
    '开团了': 'team fight started',
    '开团了集合': 'team fight, group up',
    '准备开团': 'ready to engage',
    '要开团了': 'about to engage',
    '集合开团': 'group up and engage',
    '打团了集合': 'teamfight, group up',
    '集合准备打团': 'group up for fight',
    '先手控制再输出': 'initiate with cc then dps',
    '保护后排别被切': 'protect backline',
    '等我跳刀先手': 'wait for my blink',
    '大招好了可以打': 'ult ready lets fight',
    '他们开雾了小心': 'they smoked be careful',
    '分散站位别被大': 'spread out',
    '集火秒掉大哥': 'focus their carry',
    '撤退别打了': 'retreat stop fighting',
    '追击别让他们跑': 'chase dont let them escape',
    '推高地了集合': 'group push high ground',
    '守住下路二塔': 'defend bot tier 2',
    '带线牵制他们': 'split push pressure them',
    '拆掉中路一塔': 'take mid tier 1',
    '别让他们推高': 'dont let them push high',
    '带兵线过去': 'push the creep wave',
    '上高地上高地': 'go high ground',
    '守高地别让他们上': 'defend high ground',
    '推完这波回城': 'push then tp back',
    '先推下路再打盾': 'push bot then rosh',
    
    '让我补这波兵': 'let me last hit',
    '这波兵给我': 'give me this wave',
    '出跳刀先手': 'build blink for initiate',
    '买眼插河道': 'buy wards for river',
    '带粉抓人': 'carry dust for gank',
    '更新装备去': 'buy items then go',
    '出bkb打团': 'build bkb for fight',
    '买真眼排视野': 'buy sentry deward',
    '出羊刀控制': 'build sheepstick',
    '买雾开团': 'buy smoke for gank',
    '出金身保命': 'build ghost scepter',
    '带宝石排眼': 'carry gem for deward',
    '留大招打团': 'save ult for fight',
    '先手跳大': 'blink ult initiate',
    '用控制技能留人': 'use cc to lock down',
    '开bkb冲进去': 'pop bkb and go in',
    '放好技能别空大': 'dont miss ult',
    '留技能秒人': 'save skills for burst',
    '先放控制再输出': 'cc first then damage',
    '开启所有技能打': 'use all skills',
    '用逃生技能跑': 'use escape skill',
    '放大招清兵': 'ult clear wave',
    '插眼到河道': 'ward the river',
    '排掉他们的眼': 'deward their wards',
    '控制河道视野': 'river vision',
    '小心对面开雾': 'enemy smoke gank',
    '高地插眼防守': 'ward high ground',
    '野区插眼防抓': 'ward jungle',
    '排掉高台眼': 'deward high ground',
    '符点插眼看符': 'ward rune',
    
    'tp支援过来': 'tp help',
    '回防高地': 'defend high ground',
    '去中路支援': 'help mid',
    'tp下路帮忙': 'tp bot help',
    '回泉水补给': 'back fountain',
    'tp到泉水': 'tp fountain',
    '去边路支援': 'help sidelane',
    '回城更新装备': 'tp back items',
    '去肉山那里': 'go roshan',
    '击杀敌方英雄': 'kill enemy',
    '别送人头了': 'dont feed',
    '拿到人头了': 'got kill',
    '英雄阵亡了': 'hero died',
    '拿到一血': 'first blood',
    '被对面杀了': 'killed by enemy',
    '送了一血': 'gave first blood',
    '拿到双杀': 'double kill',
    '拿到三杀': 'triple kill',
    '被团灭': 'team wiped',
    '中单miss了': 'mid missing',
    '去下路gank': 'gank bot',
    '上路有人': 'top enemy',
    '中单被压了': 'mid pressured',
    '边路需要支援': 'sidelane help',
    '中路推进': 'push mid',
    '去游走抓人': 'roam gank',
    '中单被单杀': 'mid solo kill',
    '边路崩了': 'sidelane lost',
    '中路控符': 'mid rune',
    
    '赢了': 'we win',
    '输了': 'we lose',
    '没了': 'we lose',
    '没血': 'low hp',
    '没蓝': 'oom',
    '没魔': 'oom',
    '没大': 'no ult',
    '单': 'solo',
    
    '帮我买一个{物品}': 'buy a {物品} for me',
    '帮我买个{物品}': 'buy a {物品} for me',
    '帮我买{物品}': 'buy {物品} for me',
    '买{物品}': 'buy {物品}',
    '买个{物品}': 'buy a {物品}',
    '出{物品}': 'get {物品}',
    '出个{物品}': 'get a {物品}',
    '整把{物品}': 'get a {物品}',
    '要个{物品}': 'need a {物品}',
    '来{位置}': 'come {位置}',
    '去{位置}': 'go {位置}',
    '来抓{位置}': 'come gank {位置}',
    '去抓{位置}': 'go gank {位置}',
    '{位置}miss': '{位置} missing',
    '{英雄}去{位置}': '{英雄} go {位置}',
    '开{物品}': 'use {物品}',
    '开{物品}打': 'use {物品} and fight',
    '开{物品}跑': 'use {物品} and run',
    '{英雄}大': '{英雄} ult',
    '{英雄}大了': '{英雄} used ult',
    '{英雄}跳大': '{英雄} blink ult',
    '有{状态}': 'have {状态}',
    '没{状态}': 'no {状态}',
    '可以{动作}': 'can {动作}',
    '不能{动作}': 'cannot {动作}',
    '{英雄}去{位置}了': '{英雄} go {位置}',
    '{英雄}去{位置}': '{英雄} go {位置}',
    '去{位置}了': 'go {位置}',
    '去{位置}': 'go {位置}',
    '{英雄}去{位置}，{动作}': '{英雄} go {位置}, {动作}',

    # 基本"英雄+动作+位置"句式
    '{英雄}去上了': '{英雄} go top',
    '{英雄}去中了': '{英雄} go mid',
    '{英雄}去下了': '{英雄} go bot',
    '{英雄}到上了': '{英雄} go top',
    '{英雄}到中了': '{英雄} go mid',
    '{英雄}到下了': '{英雄} go bot',
    '{英雄}在上路': '{英雄} at top',
    '{英雄}在中路': '{英雄} at mid',
    '{英雄}在下路': '{英雄} at bot',

    # 复合句占位符模板（解决"，撤退"类问题）
    '{英雄}去上了，撤退': '{英雄} go top, disengage',
    '{英雄}去中了，撤退': '{英雄} go mid, disengage',
    '{英雄}去下了，撤退': '{英雄} go bot, disengage',
    '{英雄}去上了，{指令}': '{英雄} go top, {指令}',
    '{英雄}去中了，{指令}': '{英雄} go mid, {指令}',
    '{英雄}去下了，{指令}': '{英雄} go bot, {指令}',
    '{英雄}去{位置}了，{指令}': '{英雄} go {位置}, {指令}',
    '{英雄}在{位置}，{指令}': '{英雄} at {位置}, {指令}',

    # 更多扩展句式
    '{英雄}去{位置}发育': '{英雄} go {位置} farm',
    '{英雄}去{位置}刷钱': '{英雄} go {位置} farm',
    '{英雄}去{位置}抓': '{英雄} go {位置} gank',
    '{英雄}去{位置}gank': '{英雄} go {位置} gank',
    '{英雄}在{位置}打': '{英雄} fight at {位置}',
    '{英雄}去{位置}打': '{英雄} go {位置} fight',
    '{英雄}去{位置}推': '{英雄} go {位置} push',
    '{英雄}去{位置}发育': '{英雄} go {位置} farm',
    '去{位置}发育': 'go {位置} farm',
    '去{位置}刷钱': 'go {位置} farm',
    '去{位置}抓人': 'go {位置} gank',
    '去{位置}gank': 'go {位置} gank',
    '去{位置}打': 'go {位置} fight',
    '去{位置}推': 'go {位置} push',
}

# ==================== 短语模板（英文→中文）====================
PHRASE_TEMPLATES_EN_TO_ZH = {
    'group up for teamfight': '集合打团',
    'group up for fight': '集合打团',
    'initiate with blink dagger': '跳刀先手',
    'initiate with blink': '跳刀先手',
    'protect our carry please': '保护大哥',
    'protect our carry': '保护大哥',
    'protect the carry': '保护大哥',
    'wait for my ultimate': '等我大招',
    'wait for my ult': '等我大招',
    'ult is ready lets go': '大招好了',
    'ult is ready': '大招好了',
    'ult ready': '大招好了',
    'they used smoke be careful': '开雾小心',
    'they smoked be careful': '开雾小心',
    'spread out dont cluster': '分散',
    'spread out': '分散',
    'focus the enemy carry': '集火大哥',
    'focus their carry': '集火大哥',
    'focus carry': '集火大哥',
    'retreat to fountain': '撤退',
    'retreat': '撤退',
    'chase down the low hp': '追残血',
    'chase low hp': '追残血',
    'push high ground now': '推高地',
    'push high ground': '推高地',
    'defend the tier 2 tower': '守二塔',
    'defend tier 2': '守二塔',
    'defend tier 2 tower': '守二塔',
    'split push the lanes': '分路带线',
    'split push': '分路带线',
    'take the mid tower': '拿中塔',
    'take mid tower': '拿中塔',
    'take mid': '拿中塔',
    'dont let them push': '别推',
    'push the creep wave': '推兵线',
    'push creep wave': '推兵线',
    'go high ground together': '上高地',
    'push then go back': '推完回城',
    'push then back': '推完回城',
    'push bot then rosh': '推下打盾',
    
    # 刷钱/发育
    'im going to jungle': '打野',
    'farm dont fight': '刷钱别打',
    'farm dont fight yet': '刷钱别打',
    'let me last hit': '补刀',
    'farm ancient camps': '刷远古',
    'farm the ancient camps': '刷远古',
    'finish jungle then back': '刷完回',
    'finish jungle then back home': '刷完回',
    'dont steal my camps': '别抢野',
    'stacking the camps': '拉野',
    'give me this wave': '这波兵',
    'farm for items': '刷钱更新',
    'farm for items update': '刷钱更新',
    'farm enemy jungle': '去对面野',
    'farm jungle': '打野',
    
    # 出装/物品
    'build blink': '出跳刀',
    'build blink for initiation': '出跳刀',
    'buy wards for river': '买眼河道',
    'buy wards for river vision': '买眼河道',
    'carry dust for gank': '带粉抓人',
    'carry dust for ganking': '带粉抓人',
    'buy items then fight': '买装备打',
    'build bkb': '出bkb',
    'build bkb for teamfight': '出bkb',
    'buy sentry to deward': '买真眼',
    'buy sentry': '买真眼',
    'build sheepstick': '出羊刀',
    'build sheepstick for control': '出羊刀',
    'build ghost scepter': '出金身',
    'carry gem for deward': '带宝石',
    'carry gem for dewarding': '带宝石',
    'save ult': '留大',
    'save ult for fight': '留大',
    'blink and ult': '跳大',
    'pop bkb and fight': '开bkb',
    'pop bkb': '开bkb',
    'land your skills': '放技能',
    'land your skills properly': '放准技能',
    'save skills for burst': '留技能',
    'use all spells': '用技能',
    'use all spells now': '用技能',
    'use escape skill': '用逃生',
    'use ult to clear wave': '大清兵',
    'use ult to clear': '大清兵',
    'ult to clear wave': '大清兵',
    
    # 视野
    'ward the river': '河道眼',
    'ward the river spot': '河道眼',
    'deward': '排眼',
    'deward their wards': '排眼',
    'ward roshan': '肉山眼',
    'ward roshan pit': '肉山眼',
    'control river': '河道视野',
    'control river vision': '河道视野',
    'watch out for smoke': '小心雾',
    'ward high ground': '高地眼',
    'ward jungle': '野区眼',
    'ward jungle entrance': '野区眼',
    'deward high ground': '排高眼',
    'ward rune': '符点眼',
    'ward the rune spots': '符点眼',
    'ward rune spot': '符点眼',
    
    # 支援/tp
    'tp to help': 'tp支援',
    'tp to help now': 'tp支援',
    'tp help': 'tp支援',
    'defend high ground now': '守高地',
    'go help mid': '中支援',
    'go help mid lane': '中支援',
    'tp bot to assist': '下支援',
    'tp bot': 'tp下',
    'go top to farm': '上发育',
    'go back to fountain': '回泉水',
    'back to fountain': '回泉水',
    'tp to fountain': 'tp回',
    'tp to fountain heal': 'tp回',
    'go help sidelane': '边支援',
    'tp back': 'tp回',
    'tp back buy items': '回城买',
    'tp back for items': '回城买',
    'go to roshan': '去肉山',
    'go to roshan pit': '去肉山',
    
    # 击杀/死亡
    'kill enemy': '击杀',
    'kill the enemy hero': '击杀',
    'stop feeding': '别送',
    'stop feeding kills': '别送',
    'got the kill': '拿人头',
    'hero died': '英雄死了',
    'hero has died': '英雄死了',
    'got first blood': '一血',
    'first blood': '一血',
    'killed by enemy': '被杀',
    'killed by': '被杀',
    'gave first blood': '送一血',
    'got double kill': '双杀',
    'double kill': '双杀',
    'got triple kill': '三杀',
    'triple kill': '三杀',
    'got team wiped': '团灭',
    'team wiped': '团灭',
    'we team wiped': '被团灭',
    
    # Roshan
    'group up for roshan': '集合肉山',
    'roshan spawned': '肉山刷新',
    'roshan has spawned': '肉山刷新',
    'roshan is dead': '肉山没',
    'we got the aegis': '拿盾',
    'got the aegis': '拿盾',
    'we have aegis': '有盾',
    'have aegis': '有盾',
    'enemy taking rosh': '对面打盾',
    'enemy is taking rosh': '对面打盾',
    'contest roshan': '抢盾',
    'contest the roshan': '抢盾',
    'roshan alive': '肉山在',
    'roshan still alive': '肉山还活着',
    'prepare for rosh': '准备肉山',
    'prepare for rosh fight': '准备肉山',
    'ward near roshan': '肉山眼',
    
    # 分路
    'mid lane missing': '中miss',
    'mid lane is missing': '中miss',
    'mid missing': '中miss',
    'gank bot': '下gank',
    'gank bot lane': '下gank',
    'gank bot lane now': '下gank',
    'someone top': '上有人',
    'someone is top': '上有人',
    'top enemy': '上有人',
    'mid pressured': '中被压',
    'mid getting pressured': '中被压',
    'sidelane help': '边需支援',
    'sidelane needs help': '边需支援',
    'push mid lane': '推中',
    'push mid': '推中',
    'roam': '游走',
    'roam for ganks': '游走',
    'roam for gank': '游走',
    'mid solo kill': '中被单',
    'mid died solo': '中被单',
    'sidelane lost': '边崩',
    'sidelane is losing': '边崩',
    'mid control rune': '中控符',
    'mid control the rune': '中控符',
    'group up for fight': '集合',
    
    'go mid': '去中',
    'go top': '去上',
    'go bot': '去下',
    'go jungle': '去野',
    'push mid': '推中',
    'push top': '推上',
    'push bot': '推下',
    'defend mid': '守中',
    'defend top': '守上',
    'defend bot': '守下',
    'farm mid': '中刷',
    'farm top': '上刷',
    'farm bot': '下刷',
    
    'mid missing': '中miss',
    'top missing': '上miss',
    'bot missing': '下miss',
    'mid is missing': '中miss',
    'top is missing': '上miss',
    'bot is missing': '下miss',
    'mid miss': '中miss',
    'top miss': '上miss',
    'bot miss': '下miss',
    'qop is missing': '女王miss',
    'qop is miss': '女王miss',
    'qop miss': '女王miss',
    'is missing': 'miss了',
    'mid gank': '中去抓',
    'top gank': '上去抓',
    'bot gank': '下去抓',
    
    'mirana mid': '白虎中',
    'mirana go mid': '白虎去中',
    'am bot': '敌法下',
    'am go bot': '敌法去下',
    'doom jungle': '末日野',
    'doom go jungle': '末日去野',
    'batrider top': '蝙蝠上',
    'batrider go top': '蝙蝠去上',
    
    'buy ward': '买眼',
    'buy ward for me': '帮我买眼',
    'buy a ward': '买个眼',
    'buy a ward for me': '帮我买个眼',
    'buy two wards': '买两个眼',
    'buy two wards for me': '帮我买两个眼',
    'buy dust': '买粉',
    'buy dust for me': '帮我买粉',
    'buy smoke': '买雾',
    'buy smoke for me': '帮我买雾',
    'get blink': '出跳刀',
    'get bkb': '出bkb',
    'get a blink': '整把跳刀',
    'get a bkb': '整把bkb',
    'need pipe': '要笛子',
    'need a pipe': '要个笛子',
    'get eul': '出吹风',
    'get an eul': '出把吹风',
    'get nullifier': '出否决',
    'get a nullifier': '出把否决',
    
    'use nullifier': '开否决',
    'use glimmer': '开微光',
    'use eul': '开吹风',
    'use bkb': '开bkb',
    'use blink': '开跳刀',
    'use smoke': '开雾',
    'use ethereal': '开虚灵',
    'use satanic': '开撒旦',
    'use manta': '开分身',
    'use hex': '开羊刀',
    'use orchid': '开紫苑',
    'use bloodthorn': '开血棘',
    'use force': '开推推',
    
    'stun him': '晕他',
    'stun': '晕',
    'silence': '沉默',
    'silence him': '沉默他',
    'force him': '推他',
    'eul him': '吹他',
    'hex him': '羊他',
    
    'ravage': '抄袭大',
    'ravage used': '抄袭放大',
    'echo slam': '猛犸大',
    'black hole': '谜团大',
    'chronosphere': '虚空大',
    'blink ravage': '抄袭跳大',
    'blink echo slam': '猛犸跳大',
    'blink black hole': '谜团跳大',
    'blink chronosphere': '虚空跳大',
    
    'roshan is up': '肉山在',
    'roshan is dead': '肉山没了',
    'roshan up': '肉山在',
    'roshan dead': '肉山没了',
    'roshan about to spawn': '肉山快刷了',
    'roshan has aegis': '肉山有盾',
    
    'defend tower': '守塔',
    'push tower': '推塔',
    'defend high ground': '守高',
    'push high ground': '上高',
    'dont push high ground': '别上高',
    
    'have buyback': '有买',
    'no buyback': '没买',
    'tp here': 'tp来',
    'tp back': 'tp回',
    'tp defend': 'tp守',
    
    'farm': '刷钱',
    'jungle': '打野',
    'go jungle': '去野',
    'go farm': '去发育',
    
    'can fight': '可以打',
    'cannot fight': '打不了',
    'can push': '可以推',
    'cannot push': '推不了',
    
    'dont feed': '别送',
    'dont throw': '别浪',
    'play safe': '稳住',
    'be careful': '小心',
    'fall back': '撤退',
    'get back': '回来',
    'wait for me': '等我',
    'group up': '集合',
    'teamfight': '打团',
    'initiate': '开团',
    
    'we win': '赢了',
    'we lose': '输了',
    'low hp': '没血',
    'oom': '没蓝',
    'no ult': '没大',
    'solo': '单',
    
    'buy {item}': '买{item}',
    'buy {item} for me': '帮我买{item}',
    'buy a {item}': '买个{item}',
    'buy a {item} for me': '帮我买个{item}',
    'get {item}': '出{item}',
    'get a {item}': '出个{item}',
    'need {item}': '要{item}',
    'need a {item}': '要个{item}',
    
    'go {location}': '去{location}',
    'push {location}': '推{location}',
    'defend {location}': '守{location}',
    'farm {location}': '{location}刷',
    '{location} missing': '{location} miss',
    
    '{hero} {location}': '{hero} {location}',
    '{hero} go {location}': '{hero}去{location}',
    
    'use {item}': '开{item}',
    'use {item} and fight': '开{item}打',
    
    '{hero} ult': '{hero}大',
    '{hero} used ult': '{hero}大了',
    '{hero} blink ult': '{hero}跳大',
    
    'have {status}': '有{status}',
    'no {status}': '没{status}',
    
    'can {action}': '可以{action}',
    'cannot {action}': '不能{action}',
}

if __name__ == "__main__":
    print("=" * 50)
    print("Dota2 翻译词库 - 优化版 v3.0")
    print("=" * 50)
    print(f"核心术语（中->英）: {len(ZH_TO_EN)} 条")
    print(f"核心术语（英->中）: {len(EN_TO_ZH)} 条")
    print(f"短语模板（中->英）: {len(PHRASE_TEMPLATES_ZH_TO_EN)} 条")
    print(f"短语模板（英->中）: {len(PHRASE_TEMPLATES_EN_TO_ZH)} 条")
    print("=" * 50)
