# Dota2 翻译词库 - 只需维护一份
# 模式1 (中→英): 中文 → 英文
# 模式2 (英→中): 英文 → 中文 (自动反转)

# ==================== 位置/角色 ====================
POS_TERMS = {
    'pos1': 'carry',
    'pos2': 'mid',
    'pos3': 'offlane',
    'pos4': 'soft support',
    'pos5': 'hard support',
    'carry': 'carry',
    'core': 'core',
    'sup': 'support',
    'support': 'support',
    'initiator': 'initiator',
    'tank': 'tank',
    'melee': 'melee',
    'range': 'ranged',
    'disabler': 'disabler',
    'hard carry': 'hard carry',
    'crowd control': 'crowd control',
}

# ==================== 英雄全称+简称 ====================
HERO_TERMS = {
    # 核心英雄
    'fv': 'faceless void', 'void': 'faceless void', '虚空': 'faceless void',
    'jugg': 'juggernaut', 'juggernaut': 'juggernaut', '剑圣': 'juggernaut',
    'wk': 'wraith king', 'wraith king': 'wraith king', '骷髅王': 'wraith king',
    'snk': 'wraith king',
    'spe': 'spectre', 'spectre': 'spectre', '幽鬼': 'spectre',
    'morph': 'morphling', 'morphling': 'morphling', '水人': 'morphling',
    'gyro': 'gyrocopter', 'gyrocopter': 'gyrocopter', '飞机': 'gyrocopter',
    'bs': 'bloodseeker', 'bloodseeker': 'bloodseeker', '血魔': 'bloodseeker',
    'troll': 'troll warlord', 'troll warlord': 'troll warlord', '巨魔': 'troll warlord',
    'ursa': 'ursa', '熊战士': 'ursa',
    'clinkz': 'clinkz', '骨弓': 'clinkz',
    'drow': 'drow ranger', 'drow ranger': 'drow ranger', '小黑': 'drow ranger',
    'sniper': 'sniper', '狙击手': 'sniper',
    'am': 'anti-mage', 'anti-mage': 'anti-mage', '敌法': 'anti-mage',
    'pa': 'phantom assassin', 'phantom assassin': 'phantom assassin', '幻刺': 'phantom assassin',
    'slark': 'slark', '小鱼人': 'slark',
    'riki': 'riki', '隐形刺客': 'riki',
    'sa': 'stealth assassin',
    'weaver': 'weaver', '蚂蚁': 'weaver',
    'medusa': 'medusa', '美杜莎': 'medusa',
    'terrorblade': 'terrorblade', 'TB': 'terrorblade', '魂守': 'terrorblade',
    'naix': 'lifestealer', 'lifestealer': 'lifestealer', '瘟疫': 'lifestealer',

    # 中单英雄
    'qop': 'queen of pain', 'queen of pain': 'queen of pain', '女王': 'queen of pain',
    'storm': 'storm spirit', 'storm spirit': 'storm spirit', '蓝猫': 'storm spirit',
    'ss': 'storm spirit',
    'od': 'outworld devourer', 'outworld devourer': 'outworld devourer', '蓝猫': 'outworld devourer',
    'lesh': 'leshrac', 'leshrac': 'leshrac', '老鹿': 'leshrac',
    'pugna': 'pugna', '帕格纳': 'pugna',
    'invoker': 'invoker', '卡尔': 'invoker',
    'invo': 'invoker',
    'puck': 'puck', '精灵龙': 'puck',
    'pango': 'pangolier', 'pangolier': 'pangolier', '滚球': 'pangolier',
    'arc': 'arc warden', 'arc warden': 'arc warden', '电狗': 'arc warden',
    'viper': 'viper', '毒龙': 'viper',
    'snapfire': 'snapfire', 'snapfire': 'snapfire', 'SNK': 'snapfire',
    'razor': 'razor', '剃刀': 'razor',
    'zeus': 'zeus', 'zeus': 'zeus', '宙斯': 'zeus',
    'mk': 'zeus',
    'lina': 'lina', '火女': 'lina',
    'lion': 'lion', 'lion': 'lion', '莱恩': 'lion',
    'rubick': 'rubick', '拉比克': 'rubick',
    'nec': 'necrophos', 'necrophos': 'necrophos', '骨法': 'necrophos',
    'pudge': 'pudge', '屠夫': 'pudge',
    'sf': 'shadow fiend', 'shadow fiend': 'shadow fiend', '影魔': 'shadow fiend',

    # 劣势路
    'centaur': 'centaur warrunner', 'centaur warrunner': 'centaur warrunner', '马尔斯': 'centaur warrunner',
    'cw': 'centaur warrunner',
    'bristle': 'bristleback', 'bristleback': 'bristleback', '钢背': 'bristleback',
    'bb': 'bristleback',
    'brew': 'brewmaster', 'brewmaster': 'brewmaster', '酒仙': 'brewmaster',
    'timber': 'timbersaw', 'timbersaw': 'timbersaw', '伐木机': 'timbersaw',
    'axe': 'axe', '斧王': 'axe',
    'lc': 'legion commander', 'legion commander': 'legion commander', '军团': 'legion commander',
    'tide': 'tidehunter', 'tidehunter': 'tidehunter', '潮汐': 'tidehunter',
    'th': 'tidehunter',
    'sb': 'spirit breaker', 'spirit breaker': 'spirit breaker', '白牛': 'spirit breaker',
    'bara': 'spirit breaker',
    'ns': 'night stalker', 'night stalker': 'night stalker', '夜魔': 'night stalker',
    'slardar': 'slardar', '大鱼人': 'slardar',
    'underlord': 'underlord', '深渊': 'underlord',
    'ud': 'undying', 'undying': 'undying', '尸王': 'undying',
    'dawn': 'dawnbreaker', 'dawnbreaker': 'dawnbreaker', '马尔斯': 'dawnbreaker',
    'primalbeast': 'primal beast', 'primal beast': 'primal beast', '兽王': 'primal beast',

    # 辅助英雄
    'cm': 'crystal maiden', 'crystal maiden': 'crystal maiden', '冰女': 'crystal maiden',
    'lich': 'lich', '巫妖': 'lich',
    'wd': 'witch doctor', 'witch doctor': 'witch doctor', '巫医': 'witch doctor',
    'kotl': 'keeper of the light', 'keeper of the light': 'keeper of the light', '光法': 'keeper of the light',
    'jakiro': 'jakiro', '双头龙': 'jakiro',
    'disruptor': 'disruptor', '萨尔': 'disruptor',
    'dazzle': 'dazzle', '暗影萨满': 'dazzle',
    'oracle': 'oracle', '神谕者': 'oracle',
    'io': 'wisp', 'wisp': 'wisp', '小精灵': 'wisp',
    'mirana': 'mirana', '白虎': 'mirana',
    'pom': 'mirana',
    'batrider': 'batrider', '蝙蝠': 'batrider',
    'tusk': 'tusk', '海民': 'tusk',
    'skywrath': 'skywrath mage', 'skywrath mage': 'skywrath mage', '天怒': 'skywrath mage',
    'grim': 'grimstroke', 'grimstroke': 'grimstroke', '墨客': 'grimstroke',
    'hoodwink': 'hoodwink', 'hoodwink': 'hoodwink', '松鼠': 'hoodwink',
    'winter': 'winter wyvern', 'winter wyvern': 'winter wyvern', '冰龙': 'winter wyvern',
    'wyvern': 'winter wyvern',
    'ww': 'winter wyvern',
    'clockwerk': 'clockwerk', 'clockwerk': 'clockwerk', '发条': 'clockwerk',
    'cg': 'clockwerk',
    'techies': 'techies', '工程': 'techies',
    'techi': 'techies',
    'treant': 'treant protector', 'treant protector': 'treant protector', '树人': 'treant protector',
    'enchantress': 'enchantress', '小鹿': 'enchantress',
    'ench': 'enchantress',
    'chen': 'chen', '陈': 'chen',
    'ld': 'lone druid', 'lone druid': 'lone druid', '德鲁伊': 'lone druid',
    'druid': 'lone druid',
    'omni': 'omniknight', 'omniknight': 'omniknight', '全能': 'omniknight',
    'ok': 'omniknight',
    'dp': 'death prophet', 'death prophet': 'death prophet', '死亡': 'death prophet',
    'wl': 'warlock', 'warlock': 'warlock', '术士': 'warlock',
    'bane': 'bane', '痛苦': 'bane',
    'enigma': 'enigma', '谜团': 'enigma',
    'earthshaker': 'earthshaker', 'es': 'earthshaker', '锤': 'earthshaker',
    'nyx': 'nyx assassin', 'nyx assassin': 'nyx assassin', '小强': 'nyx assassin',
    'na': 'nyx assassin',
    'bh': 'bounty hunter', 'bounty hunter': 'bounty hunter', '赏金': 'bounty hunter',
    'earth': 'earth spirit', 'earth spirit': 'earth spirit', '土猫': 'earth spirit',
    'ember': 'ember spirit', 'ember spirit': 'ember spirit', '火猫': 'ember spirit',
    'void': 'void spirit', 'void spirit': 'void spirit', '紫猫': 'void spirit',

    # 其他
    'brood': 'broodmother', 'broodmother': 'broodmother', '蜘蛛': 'broodmother',
    'tiny': 'tiny', '小小': 'tiny',
    'sven': 'sven', '斯温': 'sven',
    'ck': 'chaos knight', '混沌': 'chaos knight',
    'ga': 'alchemist', 'alchemist': 'alchemist', '炼金': 'alchemist',
    'alch': 'alchemist',
    'beast': 'beastmaster', 'beastmaster': 'beastmaster',
    'bm': 'beastmaster',
    'coco': 'kunkka', 'kunkka': 'kunkka', '船长': 'kunkka',
    'vs': 'vengeful spirit', 'vengeful spirit': 'vengeful spirit', 'VS': 'vengeful spirit',
    'venge': 'vengeful spirit',
    'lycan': 'lycan', '狼人': 'lycan',
    'naga': 'naga siren', 'naga siren': 'naga siren', '娜迦': 'naga siren',
    'pl': 'phantom lancer', 'phantom lancer': 'phantom lancer', '小狗': 'phantom lancer',
    'willow': 'dark willow', 'dark willow': 'dark willow', '黑鸟': 'dark willow',
    'ogre': 'ogre mage', 'ogre mage': 'ogre mage', '食人魔': 'ogre mage',
    'aa': 'ancient apparition', 'aa': 'ancient apparition', '冰魂': 'ancient apparition',
    'mars': 'mars', '马斯': 'mars',
    'marci': 'marci', '马西': 'marci',
    'ringmaster': 'ringmaster', 'master': 'ringmaster',
}

# ==================== 物品装备 ====================
ITEM_TERMS = {
    '眼': 'ward',
    '守卫': 'ward',
    '假眼': 'observer ward',
    '真眼': 'sentry ward',
    '粉': 'dust',
    '显尘': 'dust',
    '雾': 'smoke',
    '诡计之雾': 'smoke',
    '开雾': 'smoke',
    'sod': 'smoke',
    '大药': 'tango',
    '吃树': 'tango',
    'tango': 'tango',
    '大药膏': 'healing salve',
    '治疗药膏': 'healing salve',
    '小蓝': 'mana bottle',
    '净化': 'clarity',
    'clarity': 'clarity',
    '芒果': 'mango',
    '仙灵': 'faerie fire',
    '大魔棒': 'magic stick',
    '魔棒': 'magic stick',
    'stick': 'magic stick',
    '瓶子': 'bottle',
    '魔瓶': 'bottle',
    '魂戒': 'soul ring',
    '骨灰': 'urn',
    '吹风': 'wind lace',
    '风衣': 'wind lace',
    '相位': 'phase boots',
    '假腿': 'power treads',
    '假肢': 'power treads',
    '飞鞋': 'boots of travel',
    'bot': 'boots of travel',
    '绿鞋': 'arcane boots',
    '秘法鞋': 'arcane boots',
    'arcane': 'arcane boots',
    '推推': 'force staff',
    'force': 'force staff',
    '微光': 'glimmer cape',
    'glimmer': 'glimmer cape',
    'cape': 'glimmer cape',
    '莲花': 'lotus orb',
    'lotus': 'lotus orb',
    '盘子': 'pavise',
    'disk': 'pavise',
    'aeon': 'pavise',
    '跳刀': 'blink dagger',
    'blink': 'blink dagger',
    'dagger': 'blink dagger',
    'bkb': 'black king bar',
    '黑黄': 'black king bar',
    '分身': 'manta style',
    '分身斧': 'manta style',
    '林肯': 'linken sphere',
    'linken': 'linken sphere',
    '晕锤': 'skull basher',
    'basher': 'skull basher',
    'mkb': 'monkey king bar',
    '大炮': 'daedalus',
    '金箍棒': 'daedalus',
    '蝴蝶': 'butterfly',
    '暗灭': 'desolator',
    'deso': 'desolator',
    '否决': 'nullifier',
    '隐刀': 'shadow blade',
    'silver edge': 'shadow blade',
    '大隐刀': 'silver edge',
    '羊刀': 'scythe of vyse',
    'scythe': 'scythe of vyse',
    'hex': 'scythe of vyse',
    '紫苑': 'orchid',
    '血棘': 'bloodthorn',
    '散失': 'diffusal blade',
    'diffusal': 'diffusal blade',
    '电锤': 'maelstrom',
    '陨星锤': 'refresher',
    'refresher': 'refresher orb',
    '撒旦': 'satanic',
    'satanic': 'satanic',
    '龙心': 'heart of tarrasque',
    'heart': 'heart of tarrasque',
    '冰眼': 'eye of skadi',
    'skadi': 'eye of skadi',
    '挑战': 'hood of defiance',
    '刃甲': 'blade mail',
    '反甲': 'blade mail',
    '先锋': 'vanguard',
    '强袭': 'assault cuirass',
    'ac': 'assault cuirass',
    '梅肯': 'mekansm',
    'mek': 'mekansm',
    '笛子': 'guardian greaves',
    'pipe': 'guardian greaves',
    'guardian': 'guardian greaves',
    '天堂': 'heaven\'s halberd',
    'halberd': 'heaven\'s halberd',
    '雷锤': 'mjollnir',
    '大电': 'mjollnir',
    '臂章': 'armlet',
    '血精石': 'bloodstone',
    '血精': 'bloodstone',
    '辉耀': 'radiance',
    'radiance': 'radiance',
    '狂战': 'battlefury',
    'bf': 'battlefury',
    '点金': 'hand of midas',
    'midas': 'hand of midas',
    '圣剑': 'divine rapier',
    'rapier': 'divine rapier',
    '大根': 'dagon',
    'dagon': 'dagon',
    '支配': 'helm of dominator',
    '大支配': 'helm of dominator',
    '坚韧球': 'perseverance',
    'eul': 'eul\'s divinity',
    '大吹风': 'wind waker',
    'wind waker': 'wind waker',
    '缚灵索': 'gleipnir',
    'gleipnir': 'gleipnir',
    '冰甲': 'shiva\'s guarding',
    'shiva': 'shiva\'s guarding',
    'tp': 'town portal',
    '回城': 'town portal',
    '传送': 'town portal',
    '买活': 'buyback',
    'bb': 'buyback',
    '补刀斧': 'quelling blade',
    '穷鬼盾': 'poor man\'s shield',
    '天鹰': 'ring of aquila',
    '战鼓': 'drum of endurance',
    '勋章': 'medallion of courage',
    '祭品': 'vladmir\'s offering',
    'vlad': 'vladmir\'s offering',
}

# ==================== 游戏机制/地图 ====================
MAP_TERMS = {
    '肉山': 'roshan',
    'rs': 'roshan',
    'roshan': 'roshan',
    '盾': 'aegis',
    'aegis': 'aegis',
    '不朽盾': 'aegis',
    '超级兵': 'mega creep',
    'mega': 'mega creep',
    '兵营': 'barracks',
    'barracks': 'barracks',
    '塔': 'tower',
    '基地': 'ancient',
    'base': 'ancient',
    '高地': 'high ground',
    'hg': 'high ground',
    '前哨': 'outpost',
    'outpost': 'outpost',
    '野区': 'jungle',
    'jungle': 'jungle',
    '打野': 'jungle',
    '远古': 'ancient camp',
    'ancients': 'ancient camp',
    '上路': 'top lane',
    'top': 'top lane',
    '下路': 'bottom lane',
    'bot': 'bottom lane',
    '中路': 'mid lane',
    'mid': 'mid lane',
    'lane': 'lane',
    '河道': 'river',
    '符点': 'rune spot',
    '神符': 'rune',
    'rune': 'rune',
    '赏金': 'bounty rune',
    'bounty': 'bounty rune',
    '双倍': 'double damage',
    'dd': 'double damage',
    '急速': 'haste',
    'haste': 'haste',
    '隐身': 'invisibility',
    'invis': 'invisibility',
    '恢复': 'regeneration',
    'regen': 'regeneration',
    '护盾': 'shield',
    'shield': 'shield',
    '奥术': 'arcane',
    '幻象': 'illusion',
    'illu': 'illusion',
    '智慧': 'wisdom',
    'wisdom': 'wisdom',
    '疗伤莲花': 'lotus',
}

# ==================== 战术用语 ====================
TACTICAL_TERMS = {
    'gank': 'gank',
    '抓人': 'gank',
    '游走': 'roam',
    'roam': 'roam',
    '支援': 'rotate',
    'rotate': 'rotate',
    '先手': 'initiate',
    'initiate': 'initiate',
    '后手': 'follow up',
    '推塔': 'push tower',
    'push': 'push',
    '拆塔': 'destroy tower',
    '打塔': 'hit tower',
    '打团': 'teamfight',
    '团战': 'teamfight',
    'team fight': 'teamfight',
    '带线': 'split push',
    'split': 'split push',
    'rat': 'split push',
    '集合': 'group',
    'stick': 'group',
    '抱团': 'group',
    'bait': 'bait',
    '勾引': 'bait',
    '保护': 'protect',
    'protect': 'protect',
    '防守': 'defend',
    'defend': 'defend',
    '放弃': 'give up',
    '视野': 'vision',
    'vision': 'vision',
    '风筝': 'kite',
    'kite': 'kite',
    '换血': 'trade',
    'trade': 'trade',
    '深入': 'dive',
    'dive': 'dive',
    '刷钱': 'farm',
    'farm': 'farm',
    '打钱': 'farm',
    '发育': 'farm',
    '输出': 'damage',
    '补刀': 'last hit',
    'lh': 'last hit',
    'last hit': 'last hit',
    '反补': 'deny',
    'deny': 'deny',
    '堆野': 'stack',
    'stack': 'stack',
    '拉野': 'pull',
    'pull': 'pull',
    '控线': 'control lane',
    '反眼': 'deward',
    'deward': 'deward',
    '反制': 'counter',
    'counter': 'counter',
    '前期': 'early game',
    '后期': 'late game',
    '小兵': 'creeps',
    'creeps': 'creeps',
    '中立': 'neutrals',
    'neutrals': 'neutral creeps',
    '肉': 'tank',
    '肉盾': 'tank',
    '核心': 'carry',
    '大哥': 'carry',
    '辅助': 'support',
    '酱油': 'support',
    '劣势路': 'offlane',
    '优势路': 'safe lane',
    'safe lane': 'safe lane',
    'offlane': 'offlane',
    'miss': 'miss',
    '消失': 'missing',
    '小心': 'careful',
    '注意': 'watch out',
    '撤退': 'retreat',
    'back': 'retreat',
    '别送': 'dont feed',
    '别浪': 'dont throw',
    '稳住': 'play safe',
    '上高': 'push high ground',
    '上高地': 'push high ground',
}

# ==================== 技能相关 ====================
ABILITY_TERMS = {
    '技能': 'spell',
    'spell': 'spell',
    'ability': 'ability',
    '控制': 'stun',
    'stun': 'stun',
    'disable': 'disable',
    '眩晕': 'stun',
    '晕': 'stun',
    '减速': 'slow',
    'slow': 'slow',
    '沉默': 'silence',
    'silence': 'silence',
    '驱散': 'purge',
    'dispel': 'purge',
    'purge': 'purge',
    '缠绕': 'root',
    'root': 'root',
    '爆发': 'burst',
    'nuke': 'nuke',
    'blink': 'blink',
    '闪烁': 'blink',
    'talent': 'talent',
    '天赋': 'talent',
    'ult': 'ultimate',
    'ultimate': 'ultimate',
    '大招': 'ultimate',
    '有大': 'ult ready',
    '没大': 'ult on cd',
    'target': 'target',
    'ignore': 'ignore',
    '忽略': 'ignore',
    'break': 'break',
    '破坏': 'break',
}

# ==================== 常见交流 ====================
CHAT_TERMS = {
    'gg': 'gg',
    'ez': 'easy',
    'nice': 'nice',
    '谢谢': 'thanks',
    'thx': 'thanks',
    'sorry': 'sorry',
    'ok': 'ok',
    '收到': 'copy',
    '明白': 'got it',
    '等我': 'wait for me',
    '我来': 'im coming',
    '看看': 'check',
    '打盾': 'do roshan',
    '杀肉山': 'do roshan',
    '奶': 'heal',
    '加血': 'heal',
    'heal': 'heal',
    '救': 'save',
    '保': 'protect',
    '没血': 'low hp',
    '没蓝': 'out of mana',
}

# ==================== 合并所有词库 ====================
ALL_TERMS = {}
for d in [CHAT_TERMS, ABILITY_TERMS, TACTICAL_TERMS,
          MAP_TERMS, ITEM_TERMS, HERO_TERMS, POS_TERMS]:
    ALL_TERMS.update(d)

# 模式1: 中文→英文 (按长度排序，长词优先)
ZH_TO_EN = dict(sorted(ALL_TERMS.items(), key=lambda x: len(x[0]), reverse=True))

# 模式2: 英文→中文 (手动维护重要词汇)
MANUAL_EN_TO_ZH = {
    'ward': '眼',
    'observer ward': '假眼',
    'sentry ward': '真眼',
    'dust': '粉',
    'smoke': '雾',
    'smoke of deceit': '诡计之雾',
    'tango': '大药',
    'healing salve': '大药膏',
    'clarity': '净化',
    'magic stick': '魔棒',
    'bottle': '瓶子',
    'soul ring': '魂戒',
    'urn': '骨灰',
    'wind lace': '吹风',
    'phase boots': '相位',
    'power treads': '假腿',
    'boots of travel': '飞鞋',
    'arcane boots': '秘法鞋',
    'force staff': '推推',
    'glimmer cape': '微光',
    'lotus orb': '莲花',
    'pavise': '盘子',
    'blink dagger': '跳刀',
    'black king bar': '黑黄',
    'bkb': '黑黄',
    'manta style': '分身',
    'linken sphere': '林肯',
    'skull basher': '晕锤',
    'monkey king bar': 'mkb',
    'butterfly': '蝴蝶',
    'desolator': '暗灭',
    'nullifier': '否决',
    'shadow blade': '隐刀',
    'scythe of vyse': '羊刀',
    'orchid': '紫苑',
    'bloodthorn': '血棘',
    'diffusal blade': '散失',
    'maelstrom': '电锤',
    'refresher orb': '陨星锤',
    'satanic': '撒旦',
    'heart of tarrasque': '龙心',
    'eye of skadi': '冰眼',
    'hood of defiance': '挑战',
    'blade mail': '刃甲',
    'vanguard': '先锋',
    'assault cuirass': '强袭',
    'mekansm': '梅肯',
    'guardian greaves': '笛子',
    'heaven\'s halberd': '天堂',
    'mjollnir': '雷锤',
    'armlet': '臂章',
    'bloodstone': '血精石',
    'radiance': '辉耀',
    'battlefury': '狂战',
    'hand of midas': '点金',
    'divine rapier': '圣剑',
    'dagon': '大根',
    'helm of dominator': '支配',
    'town portal': 'TP',
    'buyback': '买活',
    'roshan': '肉山',
    'aegis': '盾',
    'mega creep': '超级兵',
    'barracks': '兵营',
    'tower': '塔',
    'ancient': '基地',
    'high ground': '高地',
    'outpost': '前哨',
    'jungle': '野区',
    'ancient camp': '远古',
    'top lane': '上路',
    'bottom lane': '下路',
    'mid lane': '中路',
    'lane': '线',
    'river': '河道',
    'rune': '神符',
    'bounty rune': '赏金',
    'gank': '抓人',
    'roam': '游走',
    'push': '推',
    'farm': '刷钱',
    'carry': '核心',
    'support': '辅助',
    'stun': '控制',
    'slow': '减速',
    'silence': '沉默',
    'purge': '驱散',
    'blink': '跳刀',
    'ult': '大',
    'ultimate': '大招',
    'mid': '中路',
    'top': '上路',
    'bot': '下路',
    'tp': '传送',
    'back': '撤退',
    'care': '小心',
    'rosh': '肉山',
    'roshan': '肉山',
    'feed': '养',
    'feeder': '养',
    'miss': 'miss',
    're': '回来了',
    'gl': '好运',
    'hf': '开局好运',
    'gg': 'gg',
    'wp': '打得好',
    'gj': '好样的',
    'lol': '哈哈',
    'lul': '哈哈',
    'brb': '马上回来',
    'afk': '离开',
    'DC': '掉线',
    'bg': '提前退出',
    'noob': '傻子',
    'newbie': '新手',
    'repick': '换英雄',
    'courier': '信使',
    'creeps': '小兵',
    'neutrals': '野怪',
    'towers': '塔',
    'rax': '兵营',
    'mega': '超级兵',
    'buyback': '买活',
    'aegis': '不朽盾',
    'cheese': '奶酪',
    'gem': '宝石',
    'dust': '粉',
    'smoke': '雾',
    'ward': '眼',
    'sentry': '岗哨',
    'obs': '眼',
    'bkb': '黑皇',
    'ab': '阿托斯',
    'bf': '狂战',
    'diff': '刃甲',
    'vanguard': '先锋',
    'helm': '魂戒',
    'basher': '碎颅锤',
    'deso': '暗灭',
    'daedalus': '大炮',
    'butterfly': '蝴蝶',
    'rapier': '圣剑',
    'mkb': '金箍棒',
    'snk': '大僵尸',
    'orb': '弹射器',
    'go home': '回家',
    'gohome': '回家',
    'go mid': '去中',
    'gomid': '去中',
    'go top': '去上',
    'gotop': '去上',
    'go bot': '去下',
    'gobot': '去下',
    'just': '只是',
    'qopis': '女王',
    'go forest': '去野',
    'stay back': '往后',
    'get back': '回来',
    'nice play': '打得好',
    'well played': '打得好',
    'good game': '好局',
    'well game': '好局',
    'easy': '简单',
    'ez': '简单',
    'ez game': '简单局',
    'gg wp': 'gg打得好',
    'nice try': '尝试得好',
    'omg': '天啊',
    'omfg': '天啊',
    'wow': '哇',
    'damn': 'damn',
    'haha': '哈哈',
    'hahaha': '哈哈哈',
    'hehe': '呵呵',
    'please': '请',
    'pls': '请',
    'sry': '抱歉',
    'sorry': '抱歉',
    'thx': '谢谢',
    'thanks': '谢谢',
    'ty': '谢谢',
    'np': '不客气',
    'no problem': '不客气',
    'ok': '好',
    'okay': '好',
    'yes': '是',
    'is': '是',
    'are': '是',
    'and': '和',
    'sleep': '睡觉',
    'missing': 'miss',
    'miss': 'miss',
    'no': '不',
    'y': '是',
    'n': '不',
    'wait': '等一下',
    'wait me': '等我',
    'wait for me': '等我',
    'need help': '需要帮助',
    'help me': '帮我',
    'help': '帮忙',
    'bait': '钓鱼',
    'stack': '拉野',
    'pull': '拉野',
    'deny': '反补',
    'last hit': '正补',
    'lh': '正补',
    # 英雄简称
    'qop': '女王',
    'void': '虚空',
    'pa': '幻刺',
    'am': '敌法',
    'sf': '影魔',
    'ln': 'lion',
    'cm': '冰女',
    'lich': '巫妖',
    'wd': '巫医',
    'pudge': '屠夫',
    'axe': '斧王',
    'bb': '钢背',
    'tb': '魂守',
    'sk': '沙王',
    'es': '鱼人守卫',
    'ns': '夜魔',
    'od': '蓝猫',
    'storm': '蓝猫',
    'bs': '血魔',
    'leo': '莱恩',
    'rubick': '拉比克',
    'necro': '骨法',
    'pugna': '帕格纳',
    'zeus': '宙斯',
    'lina': '火女',
    'lion': '莱恩',
    'vs': '复仇之魂',
    '、身': '蚂蚁',
    'weaver': '蚂蚁',
    'drow': '小黑',
    'sniper': '火枪',
    'medusa': '美杜莎',
    'spectre': '幽鬼',
    'am': '敌法',
    'jug': '剑圣',
    'jugg': '剑圣',
    'wk': '骷髅王',
    'centaur': '马尔斯',
    'bristle': '钢背',
    'brew': '酒仙',
    'timber': '伐木机',
    'tide': '潮汐',
    'sb': '白牛',
    'underlord': '深渊',
    'ud': '尸王',
}

# 合并手动词库和其他反转词
AUTO_EN_TO_ZH = {v: k for k, v in ALL_TERMS.items() if isinstance(v, str)}
EN_TO_ZH = {**AUTO_EN_TO_ZH, **MANUAL_EN_TO_ZH}
EN_TO_ZH = dict(sorted(EN_TO_ZH.items(), key=lambda x: len(x[0]), reverse=True))

# ==================== 短语模板（优化版）====================
PHRASE_TEMPLATES_ZH_TO_EN = {
    '帮我买眼': 'help me buy ward',
    '帮我买个眼': 'help me buy ward',
    '买眼': 'buy ward',
    '买真眼': 'buy sentry ward',
    '买假眼': 'buy observer ward',
    '买粉': 'buy dust',
    '买雾': 'buy smoke',
    '开雾': 'use smoke',
    '开雾抓人': 'smoke and gank',
    
    '去上路': 'go top',
    '去下路': 'go bot',
    '去中路': 'go mid',
    '去野区': 'go jungle',
    '去打野': 'go jungle',
    
    '上路miss': 'top is missing',
    '下路miss': 'bot is missing',
    '中路miss': 'mid is missing',
    '上路消失了': 'top is missing',
    '下路消失了': 'bot is missing',
    '中路消失了': 'mid is missing',
    
    '打盾': 'do roshan',
    '打盾吧': 'let us do roshan',
    '杀肉山': 'kill roshan',
    '拿盾': 'get aegis',
    
    '需要视野': 'need vision',
    '这里需要视野': 'need vision here',
    '插眼': 'place ward',
    '反眼': 'deward',
    '请反眼': 'deward please',
    
    '推塔': 'push tower',
    '推塔吧': 'push the tower',
    '拆塔': 'destroy tower',
    '打塔': 'hit tower',
    
    '集合': 'group up',
    '集合打团': 'group up for teamfight',
    '抱团': 'group up',
    '打团': 'teamfight',
    
    '别送': 'do not feed',
    '别送人头': 'do not feed',
    '稳住': 'play safe',
    '稳住别浪': 'play safe',
    '别浪': 'do not throw',
    
    '我有大招': 'i have ultimate',
    '我有大': 'i have ultimate',
    '没大了': 'ultimate on cooldown',
    '大招好了': 'ultimate ready',
    
    '没蓝了': 'out of mana',
    '没蓝': 'out of mana',
    '没血了': 'low hp',
    '没血': 'low hp',
    
    '等我': 'wait for me',
    '等我一下': 'wait for me',
    '等一下': 'wait a moment',
    
    '小心': 'careful',
    '小心草丛': 'careful in bush',
    '注意': 'watch out',
    
    '上高地': 'push high ground',
    '上高': 'push high ground',
    '防守基地': 'defend the ancient',
    '守家': 'defend base',
    
    '我玩大哥': 'i play carry',
    '我玩核心': 'i play carry',
    '你打辅助': 'you play support',
    '我打辅助': 'i play support',
    
    '劣势路需要支援': 'offlane need help',
    '优势路推进': 'push safe lane',
    '中路需要帮助': 'mid need help',
    
    '打野发育': 'jungle and farm',
    '刷钱': 'farm',
    '发育': 'farm',
    
    '控线': 'control the lane',
    '控线补刀': 'control lane and last hit',
    '拉野': 'pull',
    '拉野堆野': 'pull and stack',
    '堆野': 'stack',
    
    '买活准备好了': 'buyback is ready',
    '有买活': 'have buyback',
    '没买活': 'no buyback',
    
    '肉山刷新了': 'roshan respawned',
    '不朽盾掉了': 'aegis dropped',
    '盾掉了': 'aegis dropped',
    
    '超级兵来了': 'mega creeps incoming',
    '兵营被拆': 'barracks destroyed',
    '塔没了': 'tower is down',
    '基地快没了': 'ancient low health',
    
    '买粉反隐': 'buy dust for reveal',
    '反隐': 'reveal invisible',
    
    '跳刀先手': 'blink dagger initiate',
    '推推棒救人': 'force staff to save',
    
    '黑黄杖开了': 'black king bar activated',
    '开bkb': 'activate bkb',
    
    '分身斧躲技能': 'manta style dodge',
    '羊刀控制': 'scythe of vyse disable',
    '紫苑沉默': 'orchid silence',
    '血棘爆发': 'bloodthorn burst',
    
    '龙心回血': 'heart of tarrasque regen',
    '冰眼减速': 'eye of skadi slow',
    
    '拿赏金符': 'get bounty rune',
    '双倍神符': 'double damage rune',
    '隐身神符': 'invisibility rune',
    '急速神符': 'haste rune',
    '恢复神符': 'regeneration rune',
    
    '前哨占领了': 'outpost captured',
    '远古野点': 'ancient camp',
}

HERO_ALIASES = {
    '蓝猫': 'storm spirit',
    '火猫': 'ember spirit',
    '土猫': 'earth spirit',
    '敌法': 'anti-mage',
    '敌法师': 'anti-mage',
    'am': 'anti-mage',
    '小黑': 'drow ranger',
    '血魔': 'bloodseeker',
    'bs': 'bloodseeker',
    '剑圣': 'juggernaut',
    '剑圣': 'juggernaut',
    'jk': 'juggernaut',
    '小狗': 'lifestealer',
    '小狗': 'lifestealer',
    'ls': 'lifestealer',
    '虚空': 'faceless void',
    'fv': 'faceless void',
    '水人': 'morphling',
    '猴子': 'phantom lancer',
    'pl': 'phantom lancel',
    'pa': 'phantom assassin',
    '幻刺': 'phantom assassin',
    'sf': 'shadow fiend',
    '影魔': 'shadow fiend',
    '小娜迦': 'naga siren',
    'naga': 'naga siren',
    '船长': 'kunkka',
    'coco': 'kunkka',
    '全能': 'omniknight',
    'omni': 'omniknight',
    '牛': 'earthshaker',
    '神牛': 'earthshaker',
    '潮汐': 'tidehunter',
    'tide': 'tidehunter',
    '人马': 'centaur warrunner',
    'ct': 'centaur warrunner',
    'ck': 'chaos knight',
    '混沌': 'chaos knight',
    'dp': 'death prophet',
    '死亡先知': 'death prophet',
    ' necrophos': 'necrophos',
    '死灵法': 'necrophos',
    'nec': 'necrophos',
    '骨法': 'pugna',
    '女王': 'queen of pain',
    'qop': 'queen of pain',
    '小鹿': 'enchantress',
    'enchant': 'enchantress',
    '萨尔': 'disruptor',
    'lion': 'lion',
    '恶魔巫师': 'lion',
    'lina': 'lina',
    '火女': 'lina',
    '暗牧': 'dazzle',
    'daz': 'dazzle',
    '冰女': 'crystal maiden',
    'cm': 'crystal maiden',
    '光法': 'keeper of the light',
    'kotl': 'keeper of the light',
    '先知': 'nature\'s prophet',
    'np': 'nature\'s prophet',
    'wl': 'warlock',
    '术士': 'warlock',
    'wd': 'witch doctor',
    '巫医': 'witch doctor',
    'zeus': 'zeus',
    '宙斯': 'zeus',
    'aa': 'ancient apparition',
    '冰魂': 'ancient apparition',
    '蝙蝠': 'batrider',
    'bat': 'batrider',
    '卡尔': 'invoker',
    'invoker': 'invoker',
    'tk': 'tinker',
    '修补匠': 'tinker',
    '炸弹人': 'techies',
    'techies': 'techies',
    '飞机': 'gyrocopter',
    'gyro': 'gyrocopter',
    '飞机': 'gyrocopter',
    '大娜迦': 'medusa',
    'dusa': 'medusa',
    'med': 'medusa',
    '小骷髅': 'clinkz',
    'clinkz': 'clinkz',
    '隐刺': 'riki',
    'riki': 'riki',
    '白虎': 'mirana',
    'mirana': 'mirana',
    '月女': 'mirana',
    '蚂蚁': 'weaver',
    'weaver': 'weaver',
    '毒龙': 'viper',
    'viper': 'viper',
    '剧毒': 'venomancer',
    'veno': 'venomancer',
    '赏金': 'bounty hunter',
    'bh': 'bounty hunter',
    '夜魔': 'night stalker',
    'ns': 'night stalker',
    '白牛': 'spirit breaker',
    'sb': 'spirit breaker',
    'sw': 'sven',
    '流浪剑客': 'sven',
    '斧王': 'axe',
    'axe': 'axe',
    'fw': 'axe',
    '屠夫': 'pudge',
    'pudge': 'pudge',
    '胖子': 'pudge',
    '沙王': 'sand king',
    'sk': 'sand king',
    '兽王': 'beastmaster',
    'bm': 'beastmaster',
    '钢背兽': 'bristleback',
    'bb': 'bristleback',
    '小小': 'tiny',
    'tiny': 'tiny',
    '大树': 'treant protector',
    'tp': 'treant protector',
    '海民': 'tusk',
    'tusk': 'tusk',
    '海牙': 'tusk',
    '尸王': 'undying',
    'ud': 'undying',
    'und': 'undying',
    '大屁股': 'underlord',
    'ul': 'underlord',
    '蓝胖': 'ogre magi',
    'ogre': 'ogre magi',
    'om': 'ogre magi',
    '尸王': 'undying',
    'wc3': 'witch doctor',
    'pl': 'phantom lancel',
    'tb': 'terrorblade',
    '魂守': 'terrorblade',
    'tb': 'terrorblade',
    '巨魔': 'troll warlord',
    'troll': 'troll warlord',
    '拍拍': 'ursa',
    'ursa': 'ursa',
    'vs': 'vengeful spirit',
    '复仇': 'vengeful spirit',
    '火枪': 'sniper',
    'sniper': 'sniper',
    '幽鬼': 'spectre',
    'spec': 'spectre',
    'sp': 'spectre',
    '电魂': 'razor',
    '电棍': 'razor',
    'razor': 'razor',
    '圣堂': 'templar assassin',
    'ta': 'templar assassin',
    '电狗': 'arc warden',
    'arc': 'arc warden',
    'aw': 'arc warden',
    '米波': 'meepo',
    'meepo': 'meepo',
    '熊德': 'lone druid',
    'ld': 'lone druid',
    '月骑': 'luna',
    'luna': 'luna',
    '德鲁伊': 'lone druid',
    '凤凰': 'phoenix',
    'phoenix': 'phoenix',
    '大牛': 'elder titan',
    'et': 'elder titan',
    '神灵': 'huskar',
    'sw': 'huskar',
    '军团': 'legion commander',
    'lc': 'legion commander',
    '炼金': 'alchemist',
    'alch': 'alchemist',
    '亚巴顿': 'abaddon',
    'aba': 'abaddon',
    'loa': 'abaddon',
    '死骑': 'abaddon',
    '冥魂大帝': 'wraith king',
    'wk': 'wraith king',
    'snk': 'wraith king',
    '骷髅王': 'wraith king',
    '黑鸟': 'outworld devourer',
    'od': 'outworld devourer',
    'mars': 'mars',
    '玛尔斯': 'mars',
    '墨客': 'grimstroke',
    'grim': 'grimstroke',
    '小歪': 'shadow shaman',
    'ss': 'shadow shaman',
    '小y': 'shadow shaman',
    '拉比克': 'rubick',
    'rubick': 'rubick',
    '小仙女': 'dark willow',
    'willow': 'dark willow',
    '精灵龙': 'puck',
    'puck': 'puck',
    '天怒': 'skywrath mage',
    'sky': 'skywrath mage',
    '风行': 'windranger',
    'wr': 'windragger',
    '冰龙': 'winter wyvern',
    'ww': 'winter wyvern',
    '死灵龙': 'visage',
    'visage': 'visage',
    '双头龙': 'jakiro',
    'jakiro': 'jakiro',
    '老鹿': 'leshrac',
    'lesh': 'leshrac',
    '51': 'lich',
    '巫妖': 'lich',
    'lich': 'lich',
    '祸乱': 'bane',
    'bane': 'bane',
    '陈': 'chen',
    'chen': 'chen',
    '神谕': 'oracle',
    'oracle': 'oracle',
    '51': 'witch doctor',
}

GAME_TERMS = {
    '眼': 'ward',
    '侦查守卫': 'observer ward',
    '假眼': 'observer ward',
    '真眼': 'sentry ward',
    '岗哨守卫': 'sentry ward',
    '粉': 'dust',
    '显影之尘': 'dust of appearance',
    '雾': 'smoke',
    '诡计之雾': 'smoke of deceit',
    'tp': 'town portal scroll',
    '回城': 'town portal scroll',
    '回城卷': 'town portal scroll',
    '信使': 'courier',
    '鸡': 'courier',
    'tp': 'town portal scroll',
    '肉山': 'roshan',
    '不朽盾': 'aegis',
    '不朽之守护': 'aegis',
    '奶酪': 'cheese',
    '神符': 'rune',
    '赏金符': 'bounty rune',
    '双倍': 'double damage',
    'dd': 'double damage',
    '隐身': 'invisibility',
    'invis': 'invisibility',
    '急速': 'haste',
    '恢复': 'regeneration',
    'regen': 'regeneration',
    '幻象': 'illusion',
    '智慧': 'water',
    '奥术': 'arcane',
    '推塔': 'push tower',
    '防守': 'defend',
    '抓人': 'gank',
    '游走': 'gank',
    '发育': 'farm',
    '打钱': 'farm',
    '补刀': 'last hit',
    '正补': 'last hit',
    '反补': 'deny',
    '拉野': 'stack',
    '堆野': 'stack',
    '拉兵线': 'pull',
    '野区': 'jungle',
    '中路': 'mid',
    '上路': 'top',
    '下路': 'bot',
    '劣势路': 'offlane',
    '优势路': 'safelane',
    '核心': 'carry',
    '大哥': 'carry',
    '辅助': 'support',
    '中单': 'midlaner',
    '劣势路': 'offlaner',
    '肉盾': 'tank',
    '爆发': 'burst',
    '控制': 'cc',
    '先手': 'initiate',
    '逃生': 'escape',
    '推进': 'pusher',
    '没蓝': 'oom',
    '没血': 'low hp',
    '没大': 'no ult',
    '大招': 'ult',
    'ultimate': 'ult',
    '买活': 'buyback',
    '掉线': 'dc',
    '挂机': 'afk',
    '举报': 'report',
    '集火': 'focus',
    '晕': 'stun',
    '沉默': 'silence',
    '撤退': 'back',
    '小心': 'care',
    '小心': 'care',
    '回来了': 'returned',
    '好局': 'gg',
    '玩得好': 'wp',
    '漂亮': 'nice',
    '抱歉': 'sorry',
    '我的错': 'my bad',
    '卡': 'lag',
    '点赞': 'commend',
    '送人头': 'feed',
    '别送': 'dont feed',
    '稳住': 'play safe',
    '翻盘': 'comeback',
    '上头': 'tilt',
    '送优势': 'throw',
    '削弱': 'nerf',
    '增强': 'buff',
    '强势': 'op',
    '弱势': 'up',
    '天梯': 'ranked',
    '排位': 'ranked',
    '路人局': 'pub',
    '职业选手': 'pro player',
    '版本': 'patch',
    '带线': 'split push',
    '冲塔': 'dive',
    '风筝': 'kite',
    '保护': 'peel',
    '消耗': 'poke',
    '续航': 'sustain',
    '开团': 'engage',
    '撤退': 'disengage',
    '抢人头': 'ks',
    '滚雪球': 'snowball',
}

ITEM_ALIASES = {
    '假眼': 'observer ward',
    '真眼': 'sentry ward',
    '雾': 'smoke of deceit',
    '粉': 'dust of appearance',
    'tp': 'town portal scroll',
    '回城': 'town portal scroll',
    '芒果': 'enchanted mango',
    '吃树': 'tango',
    '树': 'tango',
    '大药': 'healing salve',
    '药膏': 'healing salve',
    '小蓝': 'clarity',
    '净化': 'clarity',
    '树枝': 'iron branch',
    '魔棒': 'magic stick',
    '魔杖': 'magic wand',
    '假腿': 'power treads',
    '假腿': 'power treads',
    'pt': 'power treads',
    '相位': 'phase boots',
    '秘法': 'arcane boots',
    '点金': 'hand of midas',
    'midas': 'hand of midas',
    '狂战': 'battle fury',
    'bf': 'battle fury',
    '漩涡': 'maelstrom',
    '雷锤': 'mjollnir',
    '黯灭': 'desolator',
    'deso': 'desolator',
    '大炮': 'daedalus',
    'crit': 'daedalus',
    '金箍棒': 'monkey king bar',
    'mkb': 'monkey king bar',
    '蝴蝶': 'butterfly',
    '辉耀': 'radiance',
    '圣剑': 'divine rapier',
    'rapier': 'divine rapier',
    'bkb': 'black king bar',
    '黑黄': 'black king bar',
    '黑皇': 'black king bar',
    '林肯': 'linken sphere',
    'linken': 'linken sphere',
    '血棘': 'bloodthorn',
    '否决': 'nullifier',
    '羊刀': 'scythe of vyse',
    '紫苑': 'orchid malevolence',
    'orchid': 'orchid malevolence',
    '血精': 'bloodstone',
    '血精石': 'bloodstone',
    '西瓦': 'shiva guard',
    'shiva': 'shiva guard',
    '龙心': 'heart of tarrasque',
    'heart': 'heart of tarrasque',
    '强袭': 'assault cuirass',
    'ac': 'assault cuirass',
    '撒旦': 'satanic',
    '冰眼': 'eye of skadi',
    'skadi': 'eye of skadi',
    '大根': 'aghanim scepter',
    '神杖': 'aghanim scepter',
    'aghs': 'aghanim scepter',
    '魔晶': 'aghanim shard',
    'shard': 'aghanim shard',
    '跳刀': 'blink dagger',
    'blink': 'blink dagger',
    '推推': 'force staff',
    '推杖': 'force staff',
    '风杖': 'eul scepter of divinity',
    'eul': 'eul scepter of divinity',
    'dagon': 'dagon',
    '死灵书': 'necronomicon',
    'necro': 'necronomicon',
    '纷争': 'veil of discord',
    'veil': 'veil of discord',
    '笛子': 'pipe of insight',
    'pipe': 'pipe of insight',
    '赤红': 'crimson guard',
    'crimson': 'crimson guard',
    '莲花': 'lotus orb',
    'lotus': 'lotus orb',
    '炎阳': 'solar crest',
    'solar': 'solar crest',
    '祭品': 'vladimir offering',
    'vlad': 'vladimir offering',
    '梅肯': 'mekansm',
    'mek': 'mekansm',
    '挑战': 'hood of defiance',
    'hood': 'hood of defiance',
    '刃甲': 'blade mail',
    '先锋': 'vanguard',
    '散夜': 'sange and yasha',
    'sny': 'sange and yasha',
    '分身': 'manta style',
    'manta': 'manta style',
    '散失': 'diffusal blade',
    'diffusal': 'diffusal blade',
    '虚灵': 'ethereal blade',
    'e blade': 'ethereal blade',
    '阿托斯': 'rod of atos',
    'atos': 'rod of atos',
    '缚灵': 'gleipnir',
    'gleipnir': 'gleipnir',
    '玲珑心': 'octarine core',
    'octarine': 'octarine core',
    '刷新': 'refresher orb',
    'refresher': 'refresher orb',
    '飞鞋': 'boots of travel',
    'bot': 'boots of travel',
    'travel': 'boots of travel',
    '支配': 'helm of the dominator',
    'hotd': 'helm of the dominator',
    '霸者': 'helm of the overlord',
    'overlord': 'helm of the overlord',
    '龙枪': 'dragon lance',
    'lance': 'dragon lance',
    '飓风': 'hurricane pike',
    'pike': 'hurricane pike',
    '隐刀': 'shadow blade',
    'sb': 'shadow blade',
    '银月': 'silver edge',
    '否决': 'nullifier',
    '宝石': 'gem of true sight',
    'gem': 'gem of true sight',
    '卫士': 'guardian greaves',
    'gg': 'guardian greaves',
    '疯脸': 'mask of madness',
    'mom': 'mask of madness',
}

PHRASE_TEMPLATES_ZH_TO_EN.update({
    '开雾': 'use smoke',
    '开雾抓人': 'smoke and gank',
    '去抓人': 'go gank',
    '来抓中': 'gank mid',
    '来抓': 'come gank',
    '推塔': 'push tower',
    '推上塔': 'push top tower',
    '推中塔': 'push mid tower',
    '推下塔': 'push bot tower',
    '守塔': 'defend tower',
    '守高地': 'defend high ground',
    '高地下': 'high ground',
    '打肉山': 'do roshan',
    '杀肉山': 'kill roshan',
    '拿盾': 'get aegis',
    '有盾': 'have aegis',
    '盾掉了': 'aegis dropped',
    '奶酪': 'have cheese',
    '没盾': 'no aegis',
    '他们野区': 'their jungle',
    '我们野区': 'our jungle',
    '帮我拉野': 'stack camps for me',
    '需要支援': 'need backup',
    '撤退': 'fall back',
    '塔下打': 'fight under tower',
    '别打团': 'dont fight',
    '等大招': 'wait for ult',
    '我来先手': 'ill initiate',
    '集火': 'focus',
    '集火他': 'focus him',
    '先杀辅助': 'kill support first',
    '带线': 'split push',
    '抱团': 'group up',
    '结束比赛': 'end the game',
    '我现在没蓝': 'im oom',
    '大招冷却中': 'ult on cooldown',
    '没蓝打架': 'no mana for fight',
    '血少需要治疗': 'low hp need heal',
    '买活中': 'buying back',
    '没钱买活': 'no buyback gold',
    'tp冷却中': 'tp on cooldown',
    '没tp': 'no tp scroll',
    '信使运送中': 'courier delivering',
    '需要信使': 'need courier',
    '插眼中': 'warding',
    '反眼中': 'dewarding',
    '拉野中': 'stacking',
    '拉兵线中': 'pulling',
    '打野中': 'farming jungle',
    '推线中': 'pushing lane',
    '需要眼': 'need wards',
    '需要宝石': 'need gem',
    '给个吃树': 'share tango',
    '给我小蓝': 'give me clarity',
    '需要大药': 'need salve',
    '出梅肯': 'buy mek',
    '我们需要笛子': 'we need pipe',
    '出bkb': 'get bkb',
    '需要反隐': 'need detection',
    '升级信使': 'upgrade courier',
    '打得好': 'well played',
    '杀得好': 'nice kill',
    '干得漂亮': 'good job',
    '抱歉我的错': 'sorry my bad',
    '别喷人': 'dont flame',
    '保持积极': 'stay positive',
    '我们能赢': 'we can win',
    '别放弃': 'dont give up',
    '举报': 'report',
    '给我点赞': 'commend me',
    '好局打得好': 'gg wp',
    '下局祝好运': 'gl hf next',
    '没蓝': 'oom',
    '蓝少': 'low mana',
    '需要蓝': 'need mana',
    '血少': 'low hp',
    '有买活': 'have buyback',
    '没买活': 'no buyback',
    '来打团': 'come fight',
    '别浪': 'dont throw',
    '稳住别浪': 'play safe dont throw',
    '开始打团': 'fight',
    '打团': 'teamfight',
    '入侵野区': 'invade jungle',
    '偷盾': 'steal aegis',
    '偷塔': 'backdoor',
    '做眼': 'place ward',
    '这里插眼': 'ward here',
    '那里插眼': 'ward there',
    '他们这里有眼': 'they have ward here',
    '反眼': 'deward',
    '这里反眼': 'deward here',
    '清掉他们眼': 'clear their wards',
    '买眼': 'buy ward',
    '买真眼': 'buy sentry',
    '买粉': 'buy dust',
    '开5': 'use smoke',
    '隐身了': 'invisible',
    '没隐身了': 'not invisible anymore',
    '看得见': 'revealed',
    '我来了': 'im coming',
    '等等我': 'wait for me',
    ' Follow Me': 'follow me',
    ' direct': 'direct',
    '别补了': 'stop last hitting',
    '给我让经验': 'share experience',
    '别抢': 'dont ks',
    '我来清': 'i will clear',
    '我来打': 'i will hit',
    '我来扛': 'i will tank',
    '我来奶': 'i will heal',
    '给我盾': 'shield me',
    '给我攻': 'buff me',
    '加速': 'haste',
    '减速': 'slow',
    '免疫': 'immune',
    '魔免': 'magic immune',
    '物免': 'physical immune',
    '开bkb': 'use bkb',
    '开林肯': 'use linken',
    '开否决': 'use nullifier',
    '开紫苑': 'use orchid',
    '开羊刀': 'use hex',
    '开风杖': 'use eul',
    '开推推': 'use force',
    '开跳刀': 'use blink',
    '开微光': 'use glimmer',
    '开盘子': 'use lotus',
    '开吹风': 'use hurricane pike',
    '开否决': 'use nullifier',
    '开血棘': 'use bloodthorn',
    '开撒旦': 'use satanic',
    '开分身': 'use manta',
    '开晕': 'use stun',
    '开隐': 'use invis',
    '没大了': 'ult on cooldown',
    '大有cd': 'ult on cooldown',
    '大有好了': 'ult ready',
    '好了': 'ready',
    '没好': 'not ready',
    '可以打': 'can fight',
    '不可以打': 'cannot fight',
    '能打': 'can fight',
    '不能打': 'cannot fight',
    '差距': '差距',
    '太菜': 'noob',
    '菜': 'noob',
    '会不会玩': 'can you play',
    '你在干嘛': 'what are you doing',
    '为什么不上': 'why not engage',
    '为什么要跑': 'why run',
    '上啊': 'go go go',
    '干他': 'kill them',
    '弄他': 'kill them',
    '跑了': 'he ran',
    '追': 'chase',
    '别追': 'dont chase',
    '控肉山': 'control roshan',
    '肉山有盾': 'roshan has aegis',
    '肉山没盾': 'roshan no aegis',
    '肉山要刷了': 'roshan about to spawn',
    '肉山刷了': 'roshan spawned',
    '远古': 'ancient',
    '远古野': 'ancient camp',
    '大野': 'large camp',
    '小野': 'small camp',
    '野点': 'camp',
    '清野': 'clear jungle',
    '清线': 'clear lane',
    '收线': 'farm lane',
    '收野': 'farm jungle',
    '钻野': 'go jungle',
    '别打野': 'dont jungle',
    '来推': 'come push',
    '来守': 'come defend',
    '来打': 'come fight',
    'miss': 'missing',
    '不见了': 'missing',
    '路上': 'on the way',
    '到了': 'here',
    '这里': 'here',
    '那里': 'there',
    '这': 'here',
    '那': 'there',
    '去': 'go',
    '来': 'come',
    '回': 'back',
    '去高地': 'go high ground',
    '下高地': 'go low ground',
    '远古要刷': 'ancient about to spawn',
    '远古刷了': 'ancient spawned',
    '野要刷了': 'camp about to spawn',
    '野刷了': 'camp spawned',
    '收远古': 'farm ancient',
    '打远古': 'do ancient',
    '守': 'defend',
    '攻': 'push',
    '打': 'hit',
    '杀': 'kill',
    '抓': 'gank',
    '推': 'push',
    '清': 'clear',
    '收': 'farm',
    '插眼': 'place ward',
    '反眼': 'deward',
    '买眼': 'buy ward',
    '开雾': 'use smoke',
    '开bkb': 'use bkb',
    '开微光': 'use glimmer',
    '开撒旦': 'use satanic',
    '开分身': 'use manta',
    '推塔': 'push tower',
    '上高': 'push high ground',
    '下高': 'push low ground',
    '高地': 'high ground',
    '门牙': 'tower',
    '兵营': 'barracks',
    '超级兵': 'mega creep',
    '超级兵来了': 'mega creeps',
    '兵营': 'barracks',
    '兵营被拆': 'barracks down',
    '塔': 'tower',
    '塔被拆': 'tower down',
    '塔没了': 'tower down',
    '基地': 'ancient',
    '家': 'ancient',
    '基地没了': 'ancient low',
    '家没了': 'ancient low',
    '赢了': 'we win',
    '输了': 'we lose',
    '赢了赢了': 'gg',
    '输了输了': 'gg',
    '可以赢了': 'can end',
    '可以结束了': 'can end now',
    '别浪': 'dont throw',
    '稳住': 'play safe',
    '别冲动': 'dont overextend',
    '猥琐': 'play safe',
    '浪啥': 'why throw',
    '别装': 'dont show off',
    '发育': 'farm',
    '刷': 'farm',
    '钱': 'gold',
    '经验': 'exp',
    '等级': 'level',
    '等级': 'level',
    '装备': 'item',
    '装备': 'item',
    '鞋子': 'boots',
    '鞋': 'boots',
    '属性': 'stat',
    '力量': 'strength',
    '敏捷': 'agility',
    '智力': 'intelligence',
    '力量': 'str',
    '敏捷': 'agi',
    '智力': 'int',
    '攻击': 'attack',
    '护甲': 'armor',
    '魔抗': 'magic resistance',
    '生命': 'hp',
    '魔法': 'mana',
    '移速': 'move speed',
    '攻速': 'attack speed',
    '伤害': 'damage',
    'dps': 'dps',
})

NEW_PHRASE_TEMPLATES_EN_TO_ZH_FIXED = {
    'lets gank mid': '我们来抓中',
    'push top tower': '推上塔',
    'defend bottom': '守下路',
    'go roshan now': '现在打肉山',
    'smoke gank': '开雾抓人',
    'ward their jungle': '他们野区插眼',
    'deward here': '这里反眼',
    'stack camps for me': '帮我拉野',
    'need backup': '需要支援',
    'fall back': '撤退',
    'fight under tower': '塔下打',
    'dont fight': '别打团',
    'wait for ult': '等大招',
    'ill initiate': '我来先手',
    'focus their carry': '集火他们大哥',
    'kill support first': '先杀辅助',
    'split push': '带线',
    'group up': '抱团',
    'high ground defense': '守高地',
    'end the game': '结束比赛',
    'im oom': '我没蓝了',
    'ult on cooldown': '大招冷却中',
    'no mana for fight': '没蓝打架',
    'low hp need heal': '血少需要治疗',
    'buying back': '买活中',
    'no buyback gold': '没钱买活',
    'tp on cooldown': 'tp冷却中',
    'no tp scroll': '没tp',
    'courier delivering': '信使运送中',
    'need courier': '需要信使',
    'warding': '插眼中',
    'dewarding': '反眼中',
    'stacking': '拉野中',
    'pulling': '拉兵线中',
    'farming jungle': '打野中',
    'pushing lane': '推线中',
    'need wards': '需要眼',
    'need gem': '需要宝石',
    'share tango': '给个吃树',
    'give me clarity': '给我小蓝',
    'need salve': '需要大药',
    'buy mek': '出梅肯',
    'we need pipe': '我们需要笛子',
    'get bkb': '出bkb',
    'need detection': '需要反隐',
    'upgrade courier': '升级信使',
    'well played': '打得好',
    'nice kill': '杀得好',
    'good job': '干得漂亮',
    'sorry my bad': '抱歉我的错',
    'dont flame': '别喷人',
    'stay positive': '保持积极',
    'we can win': '我们能赢',
    'dont give up': '别放弃',
    'report': '举报',
    'commend me': '给我点赞',
    'gg wp': '好局打得好',
    'gl hf next': '下局祝好运',
    'no ult': '没大',
    'ult ready': '大招好了',
    'no buyback': '没买活',
    'have buyback': '有买活',
    'buyback ready': '买活好了',
    'care': '小心',
    'back': '撤退',
    'go': '上',
    'focus': '集火',
    'stun': '晕',
    'silence': '沉默',
    'ward here': '这里插眼',
    'need vision': '需要视野',
    'deward': '反眼',
    'stack ancients': '拉远古',
    'stack camps': '拉野',
    'push now': '现在推',
    'defend high ground': '守高地',
    'go roshan': '打肉山',
    'check roshan': '看肉山',
    'aegis on': '有盾',
    'cheese on': '有奶酪',
    'gg': '好局',
    'gl hf': '祝好运玩得开心',
    'wp': '打得好',
    'nice': '漂亮',
    'sorry': '抱歉',
    'my bad': '我的错',
    'lag': '卡',
    'dc': '掉线',
    'afk': '挂机',
    'commend': '点赞',
    'feed': '送人头',
    'dont feed': '别送',
    'play safe': '稳住',
    'throw': '送优势',
    'tilt': '上头',
    'comeback': '翻盘',
    'nerf': '削弱',
    'buff': '增强',
    'op': '强势',
    'up': '弱势',
    'ranked': '天梯',
    'pub': '路人局',
    'pro player': '职业选手',
    'patch': '版本',
    'dive': '冲塔',
    'kite': '风筝',
    'peel': '保护',
    'poke': '消耗',
    'sustain': '续航',
    'engage': '开团',
    'disengage': '撤退',
    'ks': '抢人头',
    'snowball': '滚雪球',
    'missing': '消失',
    'mia': '消失',
    'returned': '回来了',
    'care': '小心',
    'b': '撤退',
    'back': '撤退',
    'go': '上',
    'focus': '集火',
    'stun': '晕',
    'ult ready': '大招好了',
    'no ult': '没大',
    'oom': '没蓝',
    'low mana': '蓝少',
    'need mana': '需要蓝',
    'low hp': '血少',
    'need heal': '需要治疗',
    'buyback ready': '买活好了',
    'no buyback': '没买活',
    'ward': '眼',
    'sentry': '真眼',
    'dust': '粉',
    'smoke': '雾',
    'tp': '回城',
    'roshan': '肉山',
    'aegis': '不朽盾',
    'cheese': '奶酪',
    'rune': '神符',
    'gank': '抓人',
    'farm': '发育',
    'push': '推进',
    'defend': '防守',
    'backdoor': '偷塔',
    'last hit': '补刀',
    'deny': '反补',
    'stack': '拉野',
    'pull': '拉兵线',
    'jungle': '野区',
    'lane': '分路',
    'top': '上路',
    'mid': '中路',
    'bot': '下路',
    'offlane': '劣势路',
    'safelane': '优势路',
    'carry': '大哥',
    'midlaner': '中单',
    'offlaner': '劣势路',
    'support': '辅助',
    'hard support': '硬辅',
    'soft support': '软辅',
    'tank': '肉盾',
    'nuker': '爆发',
    'disabler': '控制',
    'initiator': '先手',
    'escape': '逃生',
    'pusher': '推进',
    'creep': '小兵',
    'creeps': '小兵',
    'tower': '塔',
    'towers': '塔',
    'barracks': '兵营',
    'ancient': '基地',
    'mega creeps': '超级兵',
    'ancient low hp': '基地快没了',
    'tower down': '塔没了',
    'barracks destroyed': '兵营被拆',
    'high ground': '高地',
    'low ground': '低地',
    'roshan respawned': '肉山刷新了',
    'aegis dropped': '不朽盾掉了',
    'double damage rune': '双倍神符',
    'invisibility rune': '隐身神符',
    'haste rune': '急速神符',
    'regeneration rune': '恢复神符',
    'bounty rune': '赏金符',
    'illusion rune': '幻象神符',
    'arcane rune': '奥术神符',
    'water rune': '智慧神符',
    'we win': '赢了',
    'we lose': '输了',
    'can end': '可以赢了',
    'can end now': '可以结束了',
    'dont throw': '别浪',
    'dont overextend': '别冲动',
    'farm': '发育',
    'gold': '钱',
    'experience': '经验',
    'exp': '经验',
    'level': '等级',
    'item': '装备',
    'boots': '鞋子',
    'strength': '力量',
    'agility': '敏捷',
    'intelligence': '智力',
    'str': '力量',
    'agi': '敏捷',
    'int': '智力',
    'attack': '攻击',
    'armor': '护甲',
    'hp': '生命值',
    'mana': '魔法',
    'damage': '伤害',
}

PHRASE_TEMPLATES_EN_TO_ZH = {
    'help me buy ward': '帮我买眼',
    'help me buy': '帮我买',
    'buy ward': '买眼',
    'buy sentry ward': '买真眼',
    'buy observer ward': '买假眼',
    'buy dust': '买粉',
    'buy smoke': '买雾',
    'smoke and gank': '开雾抓人',
    'use smoke': '开雾',
    
    'go top': '去上路',
    'go bot': '去下路',
    'go mid': '去中路',
    'go jungle': '去野区',
    'go to jungle': '去野区',
    
    'top is missing': '上路消失了',
    'bot is missing': '下路消失了',
    'mid is missing': '中路消失了',
    'is missing': '消失了',
    
    'do roshan': '打肉山',
    'let us do roshan': '我们去打肉山',
    'kill roshan': '杀肉山',
    'get aegis': '拿盾',
    
    'need vision': '需要视野',
    'need vision here': '这里需要视野',
    'place ward': '插眼',
    'deward please': '请反眼',
    
    'push tower': '推塔',
    'push the tower': '推塔',
    'destroy tower': '拆塔',
    'hit tower': '打塔',
    
    'group up': '集合',
    'group up for teamfight': '集合打团',
    'teamfight': '打团',
    
    'do not feed': '别送人头',
    'play safe': '稳住',
    'do not throw': '别浪',
    
    'i have ultimate': '我有大招',
    'ultimate on cooldown': '没大了',
    'ultimate ready': '大招好了',
    
    'out of mana': '没蓝了',
    'low hp': '没血了',
    
    'wait for me': '等我一下',
    'wait a moment': '等一下',
    
    'careful': '小心',
    'careful in bush': '小心草丛',
    'watch out': '注意',
    
    'push high ground': '上高地',
    'defend the ancient': '防守基地',
    'defend base': '守家',
    
    'i play carry': '我玩大哥',
    'you play support': '你打辅助',
    'i play support': '我打辅助',
    
    'offlane need help': '劣势路需要帮助',
    'push safe lane': '优势路推进',
    'mid need help': '中路需要帮助',
    
    'jungle and farm': '打野发育',
    'farm': '刷钱',
    
    'control the lane': '控线',
    'control lane and last hit': '控线补刀',
    'pull and stack': '拉野堆野',
    'pull': '拉野',
    'stack': '堆野',
    
    'buyback is ready': '买活准备好了',
    'have buyback': '有买活',
    'no buyback': '没买活',
    
    'roshan respawned': '肉山刷新了',
    'aegis dropped': '不朽盾掉了',
    
    'mega creeps incoming': '超级兵来了',
    'barracks destroyed': '兵营被拆',
    'tower is down': '塔没了',
    'ancient low health': '基地快没了',
    
    'buy dust for reveal': '买粉反隐',
    'reveal invisible': '反隐',
    
    'blink dagger initiate': '跳刀先手',
    'force staff to save': '推推棒救人',
    
    'black king bar activated': '黑黄杖开了',
    'activate bkb': '开bkb',
    
    'manta style dodge': '分身斧躲技能',
    'scythe of vyse disable': '羊刀控制',
    'orchid silence': '紫苑沉默',
    'bloodthorn burst': '血棘爆发',
    
    'heart of tarrasque regen': '龙心回血',
    'eye of skadi slow': '冰眼减速',
    
    'get bounty rune': '拿赏金符',
    'double damage rune': '双倍神符',
    'invisibility rune': '隐身神符',
    'haste rune': '急速神符',
    'regeneration rune': '恢复神符',
    
    'outpost captured': '前哨占领了',
    'ancient camp': '远古野点',
}

for k, v in NEW_PHRASE_TEMPLATES_EN_TO_ZH_FIXED.items():
    if k not in PHRASE_TEMPLATES_EN_TO_ZH:
        PHRASE_TEMPLATES_EN_TO_ZH[k] = v
