# Dota2 翻译词库 - 只需维护一份
# 模式1 (中→英): 中文 → 英文
# 模式2 (英→中): 英文 → 中文 (自动反转)

# ==================== 位置/角色 ====================
POS_TERMS = {
    'pos1': 'carry',
    'pos2': 'mid',
    'pos3': 'offlane',
    'pos4': 'soft support',
    'pos5': 'hard support',
    'carry': 'carry',
    'core': 'core',
    'sup': 'support',
    'support': 'support',
    'initiator': 'initiator',
    'tank': 'tank',
    'melee': 'melee',
    'range': 'ranged',
    'disabler': 'disabler',
    'hard carry': 'hard carry',
    'crowd control': 'crowd control',
}

# ==================== 英雄全称+简称 ====================
HERO_TERMS = {
    # 核心英雄
    'fv': 'faceless void', 'void': 'faceless void', '虚空': 'faceless void',
    'jugg': 'juggernaut', 'juggernaut': 'juggernaut', '剑圣': 'juggernaut',
    'wk': 'wraith king', 'wraith king': 'wraith king', '骷髅王': 'wraith king',
    'snk': 'wraith king',
    'spe': 'spectre', 'spectre': 'spectre', '幽鬼': 'spectre',
    'morph': 'morphling', 'morphling': 'morphling', '水人': 'morphling',
    'gyro': 'gyrocopter', 'gyrocopter': 'gyrocopter', '飞机': 'gyrocopter',
    'bs': 'bloodseeker', 'bloodseeker': 'bloodseeker', '血魔': 'bloodseeker',
    'troll': 'troll warlord', 'troll warlord': 'troll warlord', '巨魔': 'troll warlord',
    'ursa': 'ursa', '熊战士': 'ursa',
    'clinkz': 'clinkz', '骨弓': 'clinkz',
    'drow': 'drow ranger', 'drow ranger': 'drow ranger', '小黑': 'drow ranger',
    'sniper': 'sniper', '狙击手': 'sniper',
    'am': 'anti-mage', 'anti-mage': 'anti-mage', '敌法': 'anti-mage',
    'pa': 'phantom assassin', 'phantom assassin': 'phantom assassin', '幻刺': 'phantom assassin',
    'slark': 'slark', '小鱼人': 'slark',
    'riki': 'riki', '隐形刺客': 'riki',
    'sa': 'stealth assassin',
    'weaver': 'weaver', '蚂蚁': 'weaver',
    'medusa': 'medusa', '美杜莎': 'medusa',
    'terrorblade': 'terrorblade', 'TB': 'terrorblade', '魂守': 'terrorblade',
    'naix': 'lifestealer', 'lifestealer': 'lifestealer', '瘟疫': 'lifestealer',

    # 中单英雄
    'qop': 'queen of pain', 'queen of pain': 'queen of pain', '女王': 'queen of pain',
    'storm': 'storm spirit', 'storm spirit': 'storm spirit', '蓝猫': 'storm spirit',
    'ss': 'storm spirit',
    'od': 'outworld devourer', 'outworld devourer': 'outworld devourer', '蓝猫': 'outworld devourer',
    'lesh': 'leshrac', 'leshrac': 'leshrac', '老鹿': 'leshrac',
    'pugna': 'pugna', '帕格纳': 'pugna',
    'invoker': 'invoker', '卡尔': 'invoker',
    'invo': 'invoker',
    'puck': 'puck', '精灵龙': 'puck',
    'pango': 'pangolier', 'pangolier': 'pangolier', '滚球': 'pangolier',
    'arc': 'arc warden', 'arc warden': 'arc warden', '电狗': 'arc warden',
    'viper': 'viper', '毒龙': 'viper',
    'snapfire': 'snapfire', 'snapfire': 'snapfire', 'SNK': 'snapfire',
    'razor': 'razor', '剃刀': 'razor',
    'zeus': 'zeus', 'zeus': 'zeus', '宙斯': 'zeus',
    'mk': 'zeus',
    'lina': 'lina', '火女': 'lina',
    'lion': 'lion', 'lion': 'lion', '莱恩': 'lion',
    'rubick': 'rubick', '拉比克': 'rubick',
    'nec': 'necrophos', 'necrophos': 'necrophos', '骨法': 'necrophos',
    'pudge': 'pudge', '屠夫': 'pudge',
    'sf': 'shadow fiend', 'shadow fiend': 'shadow fiend', '影魔': 'shadow fiend',

    # 劣势路
    'centaur': 'centaur warrunner', 'centaur warrunner': 'centaur warrunner', '马尔斯': 'centaur warrunner',
    'cw': 'centaur warrunner',
    'bristle': 'bristleback', 'bristleback': 'bristleback', '钢背': 'bristleback',
    'bb': 'bristleback',
    'brew': 'brewmaster', 'brewmaster': 'brewmaster', '酒仙': 'brewmaster',
    'timber': 'timbersaw', 'timbersaw': 'timbersaw', '伐木机': 'timbersaw',
    'axe': 'axe', '斧王': 'axe',
    'lc': 'legion commander', 'legion commander': 'legion commander', '军团': 'legion commander',
    'tide': 'tidehunter', 'tidehunter': 'tidehunter', '潮汐': 'tidehunter',
    'th': 'tidehunter',
    'sb': 'spirit breaker', 'spirit breaker': 'spirit breaker', '白牛': 'spirit breaker',
    'bara': 'spirit breaker',
    'ns': 'night stalker', 'night stalker': 'night stalker', '夜魔': 'night stalker',
    'slardar': 'slardar', '大鱼人': 'slardar',
    'underlord': 'underlord', '深渊': 'underlord',
    'ud': 'undying', 'undying': 'undying', '尸王': 'undying',
    'dawn': 'dawnbreaker', 'dawnbreaker': 'dawnbreaker', '马尔斯': 'dawnbreaker',
    'primalbeast': 'primal beast', 'primal beast': 'primal beast', '兽王': 'primal beast',

    # 辅助英雄
    'cm': 'crystal maiden', 'crystal maiden': 'crystal maiden', '冰女': 'crystal maiden',
    'lich': 'lich', '巫妖': 'lich',
    'wd': 'witch doctor', 'witch doctor': 'witch doctor', '巫医': 'witch doctor',
    'kotl': 'keeper of the light', 'keeper of the light': 'keeper of the light', '光法': 'keeper of the light',
    'jakiro': 'jakiro', '双头龙': 'jakiro',
    'disruptor': 'disruptor', '萨尔': 'disruptor',
    'dazzle': 'dazzle', '暗影萨满': 'dazzle',
    'oracle': 'oracle', '神谕者': 'oracle',
    'io': 'wisp', 'wisp': 'wisp', '小精灵': 'wisp',
    'mirana': 'mirana', '白虎': 'mirana',
    'pom': 'mirana',
    'batrider': 'batrider', '蝙蝠': 'batrider',
    'tusk': 'tusk', '海民': 'tusk',
    'skywrath': 'skywrath mage', 'skywrath mage': 'skywrath mage', '天怒': 'skywrath mage',
    'grim': 'grimstroke', 'grimstroke': 'grimstroke', '墨客': 'grimstroke',
    'hoodwink': 'hoodwink', 'hoodwink': 'hoodwink', '松鼠': 'hoodwink',
    'winter': 'winter wyvern', 'winter wyvern': 'winter wyvern', '冰龙': 'winter wyvern',
    'wyvern': 'winter wyvern',
    'ww': 'winter wyvern',
    'clockwerk': 'clockwerk', 'clockwerk': 'clockwerk', '发条': 'clockwerk',
    'cg': 'clockwerk',
    'techies': 'techies', '工程': 'techies',
    'techi': 'techies',
    'treant': 'treant protector', 'treant protector': 'treant protector', '树人': 'treant protector',
    'enchantress': 'enchantress', '小鹿': 'enchantress',
    'ench': 'enchantress',
    'chen': 'chen', '陈': 'chen',
    'ld': 'lone druid', 'lone druid': 'lone druid', '德鲁伊': 'lone druid',
    'druid': 'lone druid',
    'omni': 'omniknight', 'omniknight': 'omniknight', '全能': 'omniknight',
    'ok': 'omniknight',
    'dp': 'death prophet', 'death prophet': 'death prophet', '死亡': 'death prophet',
    'wl': 'warlock', 'warlock': 'warlock', '术士': 'warlock',
    'bane': 'bane', '痛苦': 'bane',
    'enigma': 'enigma', '谜团': 'enigma',
    'earthshaker': 'earthshaker', 'es': 'earthshaker', '锤': 'earthshaker',
    'nyx': 'nyx assassin', 'nyx assassin': 'nyx assassin', '小强': 'nyx assassin',
    'na': 'nyx assassin',
    'bh': 'bounty hunter', 'bounty hunter': 'bounty hunter', '赏金': 'bounty hunter',
    'earth': 'earth spirit', 'earth spirit': 'earth spirit', '土猫': 'earth spirit',
    'ember': 'ember spirit', 'ember spirit': 'ember spirit', '火猫': 'ember spirit',
    'void': 'void spirit', 'void spirit': 'void spirit', '紫猫': 'void spirit',

    # 其他
    'brood': 'broodmother', 'broodmother': 'broodmother', '蜘蛛': 'broodmother',
    'tiny': 'tiny', '小小': 'tiny',
    'sven': 'sven', '斯温': 'sven',
    'ck': 'chaos knight', '混沌': 'chaos knight',
    'ga': 'alchemist', 'alchemist': 'alchemist', '炼金': 'alchemist',
    'alch': 'alchemist',
    'beast': 'beastmaster', 'beastmaster': 'beastmaster',
    'bm': 'beastmaster',
    'coco': 'kunkka', 'kunkka': 'kunkka', '船长': 'kunkka',
    'vs': 'vengeful spirit', 'vengeful spirit': 'vengeful spirit', 'VS': 'vengeful spirit',
    'venge': 'vengeful spirit',
    'lycan': 'lycan', '狼人': 'lycan',
    'naga': 'naga siren', 'naga siren': 'naga siren', '娜迦': 'naga siren',
    'pl': 'phantom lancer', 'phantom lancer': 'phantom lancer', '小狗': 'phantom lancer',
    'willow': 'dark willow', 'dark willow': 'dark willow', '黑鸟': 'dark willow',
    'ogre': 'ogre mage', 'ogre mage': 'ogre mage', '食人魔': 'ogre mage',
    'aa': 'ancient apparition', 'aa': 'ancient apparition', '冰魂': 'ancient apparition',
    'mars': 'mars', '马斯': 'mars',
    'marci': 'marci', '马西': 'marci',
    'ringmaster': 'ringmaster', 'master': 'ringmaster',
}

# ==================== 物品装备 ====================
ITEM_TERMS = {
    '眼': 'ward',
    '守卫': 'ward',
    '假眼': 'observer ward',
    '真眼': 'sentry ward',
    '粉': 'dust',
    '显尘': 'dust',
    '雾': 'smoke',
    '诡计之雾': 'smoke',
    '开雾': 'smoke',
    'sod': 'smoke',
    '大药': 'tango',
    '吃树': 'tango',
    'tango': 'tango',
    '大药膏': 'healing salve',
    '治疗药膏': 'healing salve',
    '小蓝': 'mana bottle',
    '净化': 'clarity',
    'clarity': 'clarity',
    '芒果': 'mango',
    '仙灵': 'faerie fire',
    '大魔棒': 'magic stick',
    '魔棒': 'magic stick',
    'stick': 'magic stick',
    '瓶子': 'bottle',
    '魔瓶': 'bottle',
    '魂戒': 'soul ring',
    '骨灰': 'urn',
    '吹风': 'wind lace',
    '风衣': 'wind lace',
    '相位': 'phase boots',
    '假腿': 'power treads',
    '假肢': 'power treads',
    '飞鞋': 'boots of travel',
    'bot': 'boots of travel',
    '绿鞋': 'arcane boots',
    '秘法鞋': 'arcane boots',
    'arcane': 'arcane boots',
    '推推': 'force staff',
    'force': 'force staff',
    '微光': 'glimmer cape',
    'glimmer': 'glimmer cape',
    'cape': 'glimmer cape',
    '莲花': 'lotus orb',
    'lotus': 'lotus orb',
    '盘子': 'pavise',
    'disk': 'pavise',
    'aeon': 'pavise',
    '跳刀': 'blink dagger',
    'blink': 'blink dagger',
    'dagger': 'blink dagger',
    'bkb': 'black king bar',
    '黑黄': 'black king bar',
    '分身': 'manta style',
    '分身斧': 'manta style',
    '林肯': 'linken sphere',
    'linken': 'linken sphere',
    '晕锤': 'skull basher',
    'basher': 'skull basher',
    'mkb': 'monkey king bar',
    '大炮': 'daedalus',
    '金箍棒': 'daedalus',
    '蝴蝶': 'butterfly',
    '暗灭': 'desolator',
    'deso': 'desolator',
    '否决': 'nullifier',
    '隐刀': 'shadow blade',
    'silver edge': 'shadow blade',
    '大隐刀': 'silver edge',
    '羊刀': 'scythe of vyse',
    'scythe': 'scythe of vyse',
    'hex': 'scythe of vyse',
    '紫苑': 'orchid',
    '血棘': 'bloodthorn',
    '散失': 'diffusal blade',
    'diffusal': 'diffusal blade',
    '电锤': 'maelstrom',
    '陨星锤': 'refresher',
    'refresher': 'refresher orb',
    '撒旦': 'satanic',
    'satanic': 'satanic',
    '龙心': 'heart of tarrasque',
    'heart': 'heart of tarrasque',
    '冰眼': 'eye of skadi',
    'skadi': 'eye of skadi',
    '挑战': 'hood of defiance',
    '刃甲': 'blade mail',
    '反甲': 'blade mail',
    '先锋': 'vanguard',
    '强袭': 'assault cuirass',
    'ac': 'assault cuirass',
    '梅肯': 'mekansm',
    'mek': 'mekansm',
    '笛子': 'guardian greaves',
    'pipe': 'guardian greaves',
    'guardian': 'guardian greaves',
    '天堂': 'heaven\'s halberd',
    'halberd': 'heaven\'s halberd',
    '雷锤': 'mjollnir',
    '大电': 'mjollnir',
    '臂章': 'armlet',
    '血精石': 'bloodstone',
    '血精': 'bloodstone',
    '辉耀': 'radiance',
    'radiance': 'radiance',
    '狂战': 'battlefury',
    'bf': 'battlefury',
    '点金': 'hand of midas',
    'midas': 'hand of midas',
    '圣剑': 'divine rapier',
    'rapier': 'divine rapier',
    '大根': 'dagon',
    'dagon': 'dagon',
    '支配': 'helm of dominator',
    '大支配': 'helm of dominator',
    '坚韧球': 'perseverance',
    'eul': 'eul\'s divinity',
    '大吹风': 'wind waker',
    'wind waker': 'wind waker',
    '缚灵索': 'gleipnir',
    'gleipnir': 'gleipnir',
    '冰甲': 'shiva\'s guarding',
    'shiva': 'shiva\'s guarding',
    'tp': 'town portal',
    '回城': 'town portal',
    '传送': 'town portal',
    '买活': 'buyback',
    'bb': 'buyback',
    '补刀斧': 'quelling blade',
    '穷鬼盾': 'poor man\'s shield',
    '天鹰': 'ring of aquila',
    '战鼓': 'drum of endurance',
    '勋章': 'medallion of courage',
    '祭品': 'vladmir\'s offering',
    'vlad': 'vladmir\'s offering',
}

# ==================== 游戏机制/地图 ====================
MAP_TERMS = {
    '肉山': 'roshan',
    'rs': 'roshan',
    'roshan': 'roshan',
    '盾': 'aegis',
    'aegis': 'aegis',
    '不朽盾': 'aegis',
    '超级兵': 'mega creep',
    'mega': 'mega creep',
    '兵营': 'barracks',
    'barracks': 'barracks',
    '塔': 'tower',
    '基地': 'ancient',
    'base': 'ancient',
    '高地': 'high ground',
    'hg': 'high ground',
    '前哨': 'outpost',
    'outpost': 'outpost',
    '野区': 'jungle',
    'jungle': 'jungle',
    '打野': 'jungle',
    '远古': 'ancient camp',
    'ancients': 'ancient camp',
    '上路': 'top lane',
    'top': 'top lane',
    '下路': 'bottom lane',
    'bot': 'bottom lane',
    '中路': 'mid lane',
    'mid': 'mid lane',
    'lane': 'lane',
    '河道': 'river',
    '符点': 'rune spot',
    '神符': 'rune',
    'rune': 'rune',
    '赏金': 'bounty rune',
    'bounty': 'bounty rune',
    '双倍': 'double damage',
    'dd': 'double damage',
    '急速': 'haste',
    'haste': 'haste',
    '隐身': 'invisibility',
    'invis': 'invisibility',
    '恢复': 'regeneration',
    'regen': 'regeneration',
    '护盾': 'shield',
    'shield': 'shield',
    '奥术': 'arcane',
    '幻象': 'illusion',
    'illu': 'illusion',
    '智慧': 'wisdom',
    'wisdom': 'wisdom',
    '疗伤莲花': 'lotus',
}

# ==================== 战术用语 ====================
TACTICAL_TERMS = {
    'gank': 'gank',
    '抓人': 'gank',
    '游走': 'roam',
    'roam': 'roam',
    '支援': 'rotate',
    'rotate': 'rotate',
    '先手': 'initiate',
    'initiate': 'initiate',
    '后手': 'follow up',
    '推塔': 'push tower',
    'push': 'push',
    '拆塔': 'destroy tower',
    '打塔': 'hit tower',
    '打团': 'teamfight',
    '团战': 'teamfight',
    'team fight': 'teamfight',
    '带线': 'split push',
    'split': 'split push',
    'rat': 'split push',
    '集合': 'group',
    'stick': 'group',
    '抱团': 'group',
    'bait': 'bait',
    '勾引': 'bait',
    '保护': 'protect',
    'protect': 'protect',
    '防守': 'defend',
    'defend': 'defend',
    '放弃': 'give up',
    '视野': 'vision',
    'vision': 'vision',
    '风筝': 'kite',
    'kite': 'kite',
    '换血': 'trade',
    'trade': 'trade',
    '深入': 'dive',
    'dive': 'dive',
    '刷钱': 'farm',
    'farm': 'farm',
    '打钱': 'farm',
    '发育': 'farm',
    '输出': 'damage',
    '补刀': 'last hit',
    'lh': 'last hit',
    'last hit': 'last hit',
    '反补': 'deny',
    'deny': 'deny',
    '堆野': 'stack',
    'stack': 'stack',
    '拉野': 'pull',
    'pull': 'pull',
    '控线': 'control lane',
    '反眼': 'deward',
    'deward': 'deward',
    '反制': 'counter',
    'counter': 'counter',
    '前期': 'early game',
    '后期': 'late game',
    '小兵': 'creeps',
    'creeps': 'creeps',
    '中立': 'neutrals',
    'neutrals': 'neutral creeps',
    '肉': 'tank',
    '肉盾': 'tank',
    '核心': 'carry',
    '大哥': 'carry',
    '辅助': 'support',
    '酱油': 'support',
    '劣势路': 'offlane',
    '优势路': 'safe lane',
    'safe lane': 'safe lane',
    'offlane': 'offlane',
    'miss': 'miss',
    '消失': 'missing',
    '小心': 'careful',
    '注意': 'watch out',
    '撤退': 'retreat',
    'back': 'retreat',
    '别送': 'dont feed',
    '别浪': 'dont throw',
    '稳住': 'play safe',
    '上高': 'push high ground',
    '上高地': 'push high ground',
}

# ==================== 技能相关 ====================
ABILITY_TERMS = {
    '技能': 'spell',
    'spell': 'spell',
    'ability': 'ability',
    '控制': 'stun',
    'stun': 'stun',
    'disable': 'disable',
    '眩晕': 'stun',
    '晕': 'stun',
    '减速': 'slow',
    'slow': 'slow',
    '沉默': 'silence',
    'silence': 'silence',
    '驱散': 'purge',
    'dispel': 'purge',
    'purge': 'purge',
    '缠绕': 'root',
    'root': 'root',
    '爆发': 'burst',
    'nuke': 'nuke',
    'blink': 'blink',
    '闪烁': 'blink',
    'talent': 'talent',
    '天赋': 'talent',
    'ult': 'ultimate',
    'ultimate': 'ultimate',
    '大招': 'ultimate',
    '有大': 'ult ready',
    '没大': 'ult on cd',
    'target': 'target',
    'ignore': 'ignore',
    '忽略': 'ignore',
    'break': 'break',
    '破坏': 'break',
}

# ==================== 常见交流 ====================
CHAT_TERMS = {
    'gg': 'gg',
    'ez': 'easy',
    'nice': 'nice',
    '谢谢': 'thanks',
    'thx': 'thanks',
    'sorry': 'sorry',
    'ok': 'ok',
    '收到': 'copy',
    '明白': 'got it',
    '等我': 'wait for me',
    '我来': 'im coming',
    '看看': 'check',
    '打盾': 'do roshan',
    '杀肉山': 'do roshan',
    '奶': 'heal',
    '加血': 'heal',
    'heal': 'heal',
    '救': 'save',
    '保': 'protect',
    '没血': 'low hp',
    '没蓝': 'out of mana',
}

# ==================== 合并所有词库 ====================
ALL_TERMS = {}
for d in [CHAT_TERMS, ABILITY_TERMS, TACTICAL_TERMS,
          MAP_TERMS, ITEM_TERMS, HERO_TERMS, POS_TERMS]:
    ALL_TERMS.update(d)

# 模式1: 中文→英文 (按长度排序，长词优先)
ZH_TO_EN = dict(sorted(ALL_TERMS.items(), key=lambda x: len(x[0]), reverse=True))

# 模式2: 英文→中文 (手动维护重要词汇)
MANUAL_EN_TO_ZH = {
    'ward': '眼',
    'observer ward': '假眼',
    'sentry ward': '真眼',
    'dust': '粉',
    'smoke': '雾',
    'smoke of deceit': '诡计之雾',
    'tango': '大药',
    'healing salve': '大药膏',
    'clarity': '净化',
    'magic stick': '魔棒',
    'bottle': '瓶子',
    'soul ring': '魂戒',
    'urn': '骨灰',
    'wind lace': '吹风',
    'phase boots': '相位',
    'power treads': '假腿',
    'boots of travel': '飞鞋',
    'arcane boots': '秘法鞋',
    'force staff': '推推',
    'glimmer cape': '微光',
    'lotus orb': '莲花',
    'pavise': '盘子',
    'blink dagger': '跳刀',
    'black king bar': '黑黄',
    'bkb': '黑黄',
    'manta style': '分身',
    'linken sphere': '林肯',
    'skull basher': '晕锤',
    'monkey king bar': 'mkb',
    'butterfly': '蝴蝶',
    'desolator': '暗灭',
    'nullifier': '否决',
    'shadow blade': '隐刀',
    'scythe of vyse': '羊刀',
    'orchid': '紫苑',
    'bloodthorn': '血棘',
    'diffusal blade': '散失',
    'maelstrom': '电锤',
    'refresher orb': '陨星锤',
    'satanic': '撒旦',
    'heart of tarrasque': '龙心',
    'eye of skadi': '冰眼',
    'hood of defiance': '挑战',
    'blade mail': '刃甲',
    'vanguard': '先锋',
    'assault cuirass': '强袭',
    'mekansm': '梅肯',
    'guardian greaves': '笛子',
    'heaven\'s halberd': '天堂',
    'mjollnir': '雷锤',
    'armlet': '臂章',
    'bloodstone': '血精石',
    'radiance': '辉耀',
    'battlefury': '狂战',
    'hand of midas': '点金',
    'divine rapier': '圣剑',
    'dagon': '大根',
    'helm of dominator': '支配',
    'town portal': 'TP',
    'buyback': '买活',
    'roshan': '肉山',
    'aegis': '盾',
    'mega creep': '超级兵',
    'barracks': '兵营',
    'tower': '塔',
    'ancient': '基地',
    'high ground': '高地',
    'outpost': '前哨',
    'jungle': '野区',
    'ancient camp': '远古',
    'top lane': '上路',
    'bottom lane': '下路',
    'mid lane': '中路',
    'lane': '线',
    'river': '河道',
    'rune': '神符',
    'bounty rune': '赏金',
    'gank': '抓人',
    'roam': '游走',
    'push': '推',
    'farm': '刷钱',
    'carry': '核心',
    'support': '辅助',
    'stun': '控制',
    'slow': '减速',
    'silence': '沉默',
    'purge': '驱散',
    'blink': '跳刀',
    'ult': '大',
    'ultimate': '大招',
}

# 合并手动词库和其他反转词
AUTO_EN_TO_ZH = {v: k for k, v in ALL_TERMS.items() if isinstance(v, str)}
EN_TO_ZH = {**AUTO_EN_TO_ZH, **MANUAL_EN_TO_ZH}
EN_TO_ZH = dict(sorted(EN_TO_ZH.items(), key=lambda x: len(x[0]), reverse=True))
